onBootstrap((e) => {
  e.next()
})

cronAdd('fg-cleanup', '*/5 * * * *', () => {
  const fg = require(`${__hooks}/fg.js`)
  fg.cleanupRealtime()
  fg.cleanupRooms()
})

routerAdd('GET', '/health', (e) => {
  const fg = require(`${__hooks}/fg.js`)
  return fg.ok(e, { ok: true })
})

routerAdd('POST', '/api/fg/redeem-code', (e) => require(`${__hooks}/fg.js`).redeemCode(e))
routerAdd('POST', '/api/fg/redeem-login', (e) => require(`${__hooks}/fg.js`).redeemLogin(e))
routerAdd('POST', '/api/fg/admin-login', (e) => require(`${__hooks}/fg.js`).adminLogin(e))
routerAdd('POST', '/api/fg/mint-code', (e) => require(`${__hooks}/fg.js`).mintCode(e))
routerAdd('POST', '/api/fg/list-codes', (e) => require(`${__hooks}/fg.js`).listCodes(e))
routerAdd('POST', '/api/fg/set-code-revoked', (e) => require(`${__hooks}/fg.js`).setCodeRevoked(e))
routerAdd('POST', '/api/fg/admin-list-profiles', (e) => require(`${__hooks}/fg.js`).adminListProfiles(e))
routerAdd('POST', '/api/fg/admin-create-profile', (e) => require(`${__hooks}/fg.js`).adminCreateProfile(e))
routerAdd('POST', '/api/fg/admin-reset-profile-code', (e) => require(`${__hooks}/fg.js`).adminResetProfileCode(e))
routerAdd('POST', '/api/fg/admin-delete-profile', (e) => require(`${__hooks}/fg.js`).adminDeleteProfile(e))
routerAdd('POST', '/api/fg/livekit-token', (e) => require(`${__hooks}/fg.js`).livekitToken(e))
routerAdd('POST', '/api/fg/presence-ping', (e) => require(`${__hooks}/fg.js`).presencePing(e))
routerAdd('POST', '/api/fg/presence-list', (e) => require(`${__hooks}/fg.js`).presenceList(e))
routerAdd('POST', '/api/fg/claim-profile', (e) => require(`${__hooks}/fg.js`).claimProfile(e))
routerAdd('POST', '/api/fg/pull-seen', (e) => require(`${__hooks}/fg.js`).pullSeen(e))
routerAdd('POST', '/api/fg/push-seen', (e) => require(`${__hooks}/fg.js`).pushSeen(e))
routerAdd('POST', '/api/fg/pull-learn', (e) => require(`${__hooks}/fg.js`).pullLearn(e))
routerAdd('POST', '/api/fg/push-learn', (e) => require(`${__hooks}/fg.js`).pushLearn(e))
routerAdd('POST', '/api/fg/get-content', (e) => require(`${__hooks}/fg.js`).getContent(e))
routerAdd('POST', '/api/fg/get-roster', (e) => require(`${__hooks}/fg.js`).getRoster(e))
routerAdd('POST', '/api/fg/create-room', (e) => require(`${__hooks}/fg.js`).createRoom(e))
routerAdd('POST', '/api/fg/join-room', (e) => require(`${__hooks}/fg.js`).joinRoom(e))
routerAdd('POST', '/api/fg/host-set', (e) => require(`${__hooks}/fg.js`).hostSet(e))
routerAdd('POST', '/api/fg/room-snapshot', (e) => require(`${__hooks}/fg.js`).roomSnapshot(e))
routerAdd('POST', '/api/fg/leave-room', (e) => require(`${__hooks}/fg.js`).leaveRoom(e))
routerAdd('POST', '/api/fg/member-submit', (e) => require(`${__hooks}/fg.js`).memberSubmit(e))
routerAdd('POST', '/api/fg/collect-submissions', (e) => require(`${__hooks}/fg.js`).collectSubmissions(e))
routerAdd('POST', '/api/fg/clear-submissions', (e) => require(`${__hooks}/fg.js`).clearSubmissions(e))
