import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'high-chinese-001',
    subject: 'chinese',
    prompt: '成语“画蛇添足”是说一个人做了什么？',
    choices: [
      { id: 'a', text: '把蛇画得很漂亮' },
      { id: 'b', text: '多此一举，反倒坏了事' },
      { id: 'c', text: '画画速度特别快' },
    ],
    answer: 'b',
    explanation: '蛇本来没脚，硬给它添上脚——多余的动作反而把事办砸了。',
  },
  {
    id: 'high-chinese-002',
    subject: 'chinese',
    prompt: '“狐假虎威”里的“假”是什么意思？',
    choices: [
      { id: 'a', text: '假的、不是真的' },
      { id: 'b', text: '借、利用' },
      { id: 'c', text: '放假' },
    ],
    answer: 'b',
    explanation: '“假”在这里是“借”的意思，狐狸借着老虎的威风吓唬别的动物。',
  },
  {
    id: 'high-chinese-003',
    subject: 'chinese',
    prompt: '下面哪句话有语病（说得不通顺）？',
    choices: [
      { id: 'a', text: '我昨天看了一本很有趣的书。' },
      { id: 'b', text: '通过这次活动，使我懂得了团结。' },
      { id: 'c', text: '春天到了，花儿都开了。' },
    ],
    answer: 'b',
    explanation: '“通过……使……”一起用，句子就没主语了，去掉一个就对了。',
  },
  {
    id: 'high-chinese-004',
    subject: 'chinese',
    prompt: '“春眠不觉晓”的下一句是什么？',
    choices: [
      { id: 'a', text: '处处闻啼鸟' },
      { id: 'b', text: '夜来风雨声' },
      { id: 'c', text: '花落知多少' },
    ],
    answer: 'a',
    explanation: '出自孟浩然《春晓》：春眠不觉晓，处处闻啼鸟。',
  },
  {
    id: 'high-chinese-005',
    subject: 'chinese',
    prompt: '“重”是个多音字。下面哪个词里它读 chóng？',
    choices: [
      { id: 'a', text: '重要' },
      { id: 'b', text: '重新' },
      { id: 'c', text: '重量' },
    ],
    answer: 'b',
    explanation: '“重新”的“重”读 chóng，表示“再一次”；“重要、重量”读 zhòng。',
  },
  {
    id: 'high-chinese-006',
    subject: 'chinese',
    prompt: '“胸有成竹”形容一个人怎么样？',
    choices: [
      { id: 'a', text: '胸口长了竹子' },
      { id: 'b', text: '做事前心里早有把握' },
      { id: 'c', text: '特别喜欢吃竹笋' },
    ],
    answer: 'b',
    explanation: '画竹子前心里已经有竹子的样子了，比喻做事前心中早有谋划、很有把握。',
  },
  {
    id: 'high-chinese-007',
    subject: 'chinese',
    prompt: '“锲而不舍”是什么意思？',
    choices: [
      { id: 'a', text: '一刻也舍不得休息' },
      { id: 'b', text: '一直坚持，不放弃' },
      { id: 'c', text: '舍不得花钱' },
    ],
    answer: 'b',
    explanation: '“锲”是刻，一直刻下去不停手，比喻有恒心、坚持到底。',
  },
  {
    id: 'high-chinese-008',
    subject: 'chinese',
    prompt: '“举头望明月”的下一句是什么？',
    choices: [
      { id: 'a', text: '疑是地上霜' },
      { id: 'b', text: '低头思故乡' },
      { id: 'c', text: '床前明月光' },
    ],
    answer: 'b',
    explanation: '李白《静夜思》：举头望明月，低头思故乡。',
  },
  {
    id: 'high-chinese-009',
    subject: 'chinese',
    prompt: '“行”是多音字。“银行”的“行”读什么？',
    choices: [
      { id: 'a', text: 'xíng' },
      { id: 'b', text: 'háng' },
    ],
    answer: 'b',
    explanation: '“银行、行业”的“行”读 háng；“行走、不行”读 xíng。',
  },
  {
    id: 'high-chinese-010',
    subject: 'chinese',
    prompt: '下面哪句话没有语病？',
    choices: [
      { id: 'a', text: '他大约十二岁左右。' },
      { id: 'b', text: '我们要避免今后不再犯这种错误。' },
      { id: 'c', text: '同学们正在认真地做作业。' },
    ],
    answer: 'c',
    explanation: 'A的“大约”和“左右”重复；B“避免……不再”是双重否定说反了；C没毛病。',
  },
  {
    id: 'high-chinese-011',
    subject: 'chinese',
    prompt: '成语“守株待兔”告诉我们什么道理？',
    choices: [
      { id: 'a', text: '守在树边一定能等到兔子' },
      { id: 'b', text: '不能靠运气、靠侥幸办事' },
      { id: 'c', text: '兔子跑得很快' },
    ],
    answer: 'b',
    explanation: '农夫指望兔子再撞树而死，比喻死等好运、不肯努力，是行不通的。',
  },
  {
    id: 'high-chinese-012',
    subject: 'chinese',
    prompt: '“破釜沉舟”里的“釜”指的是什么？',
    choices: [
      { id: 'a', text: '锅' },
      { id: 'b', text: '斧头' },
      { id: 'c', text: '船' },
    ],
    answer: 'a',
    explanation: '“釜”是古代的锅。打破锅、凿沉船，断了退路，比喻下定决心不留后路。',
  },
  {
    id: 'high-chinese-013',
    subject: 'chinese',
    prompt: '“千山鸟飞绝”的下一句是什么？',
    choices: [
      { id: 'a', text: '万径人踪灭' },
      { id: 'b', text: '独钓寒江雪' },
      { id: 'c', text: '孤舟蓑笠翁' },
    ],
    answer: 'a',
    explanation: '柳宗元《江雪》：千山鸟飞绝，万径人踪灭。',
  },
  {
    id: 'high-chinese-014',
    subject: 'chinese',
    prompt: '“恍然大悟”形容的是哪种感觉？',
    choices: [
      { id: 'a', text: '突然一下子明白了' },
      { id: 'b', text: '迷迷糊糊想睡觉' },
      { id: 'c', text: '气得说不出话' },
    ],
    answer: 'a',
    explanation: '本来不懂，一下子全想通了，就是“恍然大悟”。',
  },
  {
    id: 'high-chinese-015',
    subject: 'chinese',
    prompt: '“假”是多音字。“放假”的“假”读什么？',
    choices: [
      { id: 'a', text: 'jiǎ' },
      { id: 'b', text: 'jià' },
    ],
    answer: 'b',
    explanation: '“放假、假期”读 jià；“真假、假装”读 jiǎ。',
  },
  {
    id: 'high-chinese-016',
    subject: 'chinese',
    prompt: '词语“果然”最适合填进哪个句子？',
    choices: [
      { id: 'a', text: '天气预报说会下雨，傍晚（  ）下起了大雨。' },
      { id: 'b', text: '他（  ）会来吗？我也不确定。' },
      { id: 'c', text: '请你（  ）把门关上。' },
    ],
    answer: 'a',
    explanation: '“果然”表示事情和预料的一样，正好配“预报说下雨、傍晚真的下了”。',
  },
  {
    id: 'high-chinese-017',
    subject: 'chinese',
    prompt: '下面哪一组都是近义词（意思相近）？',
    choices: [
      { id: 'a', text: '高兴 — 快乐' },
      { id: 'b', text: '寒冷 — 炎热' },
      { id: 'c', text: '黑夜 — 白天' },
    ],
    answer: 'a',
    explanation: '“高兴”和“快乐”意思相近是近义词；B、C是意思相反的反义词。',
  },
  {
    id: 'high-chinese-018',
    subject: 'chinese',
    prompt: '“滥竽充数”比喻的是什么样的人？',
    choices: [
      { id: 'a', text: '吹竽吹得特别好的人' },
      { id: 'b', text: '没真本事却混在里面凑数的人' },
      { id: 'c', text: '数数特别快的人' },
    ],
    answer: 'b',
    explanation: '南郭先生不会吹竽，却混在乐队里假装会，比喻没本事的人冒充充数。',
  },
  {
    id: 'high-chinese-019',
    subject: 'chinese',
    prompt: '“两个黄鹂鸣翠柳”的下一句是什么？',
    choices: [
      { id: 'a', text: '一行白鹭上青天' },
      { id: 'b', text: '窗含西岭千秋雪' },
      { id: 'c', text: '门泊东吴万里船' },
    ],
    answer: 'a',
    explanation: '杜甫《绝句》：两个黄鹂鸣翠柳，一行白鹭上青天。',
  },
  {
    id: 'high-chinese-020',
    subject: 'chinese',
    prompt: '下面哪句话用词不当（用错了词）？',
    choices: [
      { id: 'a', text: '他认真地听老师讲课。' },
      { id: 'b', text: '操场上突然爆发出一阵热烈的味道。' },
      { id: 'c', text: '弟弟开心地笑了起来。' },
    ],
    answer: 'b',
    explanation: '“爆发出……味道”搭配不当，应该是“爆发出热烈的掌声/欢呼”。',
  },
  {
    id: 'high-chinese-021',
    subject: 'chinese',
    prompt: '“调”是多音字。“调查”的“调”读什么？',
    choices: [
      { id: 'a', text: 'tiáo' },
      { id: 'b', text: 'diào' },
    ],
    answer: 'b',
    explanation: '“调查、调动”读 diào；“调皮、调味”读 tiáo。',
  },
  {
    id: 'high-chinese-022',
    subject: 'chinese',
    prompt: '成语“井底之蛙”用来形容什么样的人？',
    choices: [
      { id: 'a', text: '住在井里的青蛙' },
      { id: 'b', text: '见识少、眼界窄的人' },
      { id: 'c', text: '跳得特别高的人' },
    ],
    answer: 'b',
    explanation: '井底的青蛙只看得到井口那一小块天，比喻见识短浅、眼界狭小的人。',
  },
]
