import type { BattleQuestion } from '../core'

// 英语 · 低年级（一二年级，约6-8岁，给闫顺儿）
// 字母、常见单词中英对照、颜色、数字。简单、口语化、可看图。
export const items: BattleQuestion[] = [
  {
    id: 'low-english-001',
    subject: 'english',
    prompt: '“苹果”用英语怎么说呀？',
    choices: [
      { id: 'a', text: 'apple' },
      { id: 'b', text: 'banana' },
      { id: 'c', text: 'orange' },
    ],
    answer: 'a',
    explanation: 'apple 就是苹果，红红圆圆的那个～',
  },
  {
    id: 'low-english-002',
    subject: 'english',
    prompt: '小猫咪用英语叫什么？',
    choices: [
      { id: 'a', text: 'dog（小狗）' },
      { id: 'b', text: 'cat（小猫）' },
      { id: 'c', text: 'fish（鱼）' },
    ],
    answer: 'b',
    explanation: 'cat 就是猫咪，喵喵～',
  },
  {
    id: 'low-english-003',
    subject: 'english',
    prompt: '红色用英语怎么说？',
    choices: [
      { id: 'a', text: 'blue（蓝色）' },
      { id: 'b', text: 'green（绿色）' },
      { id: 'c', text: 'red（红色）' },
    ],
    answer: 'c',
    explanation: 'red 是红色，像小苹果一样～',
  },
  {
    id: 'low-english-004',
    subject: 'english',
    prompt: '数字“3”用英语怎么写？',
    choices: [
      { id: 'a', text: 'two' },
      { id: 'b', text: 'three' },
      { id: 'c', text: 'four' },
    ],
    answer: 'b',
    explanation: 'three 就是 3，one two three！',
  },
  {
    id: 'low-english-005',
    subject: 'english',
    prompt: '字母 A 后面是哪个字母？',
    choices: [
      { id: 'a', text: 'B' },
      { id: 'b', text: 'C' },
      { id: 'c', text: 'D' },
    ],
    answer: 'a',
    explanation: 'A、B、C…… A 的好朋友是 B 哦～',
  },
  {
    id: 'low-english-006',
    subject: 'english',
    prompt: '“狗狗”用英语怎么说？',
    choices: [
      { id: 'a', text: 'pig（猪）' },
      { id: 'b', text: 'dog（狗）' },
      { id: 'c', text: 'duck（鸭子）' },
    ],
    answer: 'b',
    explanation: 'dog 就是小狗，汪汪汪～',
  },
  {
    id: 'low-english-007',
    subject: 'english',
    prompt: '黄色用英语怎么说？',
    choices: [
      { id: 'a', text: 'yellow（黄色）' },
      { id: 'b', text: 'black（黑色）' },
      { id: 'c', text: 'white（白色）' },
    ],
    answer: 'a',
    explanation: 'yellow 是黄色，像小鸭子和太阳～',
  },
  {
    id: 'low-english-008',
    subject: 'english',
    prompt: '“香蕉”用英语怎么说？',
    choices: [
      { id: 'a', text: 'apple' },
      { id: 'b', text: 'banana' },
      { id: 'c', text: 'grape' },
    ],
    answer: 'b',
    explanation: 'banana 就是弯弯的香蕉～',
  },
  {
    id: 'low-english-009',
    subject: 'english',
    prompt: '数字“1”用英语怎么说？',
    choices: [
      { id: 'a', text: 'one' },
      { id: 'b', text: 'ten' },
      { id: 'c', text: 'nine' },
    ],
    answer: 'a',
    explanation: 'one 就是 1，最小的那个数～',
  },
  {
    id: 'low-english-010',
    subject: 'english',
    prompt: '蓝色用英语怎么说？（像天空一样）',
    choices: [
      { id: 'a', text: 'pink（粉色）' },
      { id: 'b', text: 'blue（蓝色）' },
      { id: 'c', text: 'brown（棕色）' },
    ],
    answer: 'b',
    explanation: 'blue 是蓝色，像晴天的大天空～',
  },
  {
    id: 'low-english-011',
    subject: 'english',
    prompt: '字母 C 后面是哪个字母？',
    choices: [
      { id: 'a', text: 'A' },
      { id: 'b', text: 'B' },
      { id: 'c', text: 'D' },
    ],
    answer: 'c',
    explanation: 'A B C D…… C 后面就是 D 啦～',
  },
  {
    id: 'low-english-012',
    subject: 'english',
    prompt: '“水”用英语怎么说？',
    choices: [
      { id: 'a', text: 'milk（牛奶）' },
      { id: 'b', text: 'water（水）' },
      { id: 'c', text: 'egg（鸡蛋）' },
    ],
    answer: 'b',
    explanation: 'water 就是水，渴了要喝 water～',
  },
  {
    id: 'low-english-013',
    subject: 'english',
    prompt: '绿色用英语怎么说？（像小草一样）',
    choices: [
      { id: 'a', text: 'green（绿色）' },
      { id: 'b', text: 'red（红色）' },
      { id: 'c', text: 'orange（橙色）' },
    ],
    answer: 'a',
    explanation: 'green 是绿色，像小草和大树～',
  },
  {
    id: 'low-english-014',
    subject: 'english',
    prompt: '数字“5”用英语怎么说？（一只手有几个手指）',
    choices: [
      { id: 'a', text: 'six' },
      { id: 'b', text: 'five' },
      { id: 'c', text: 'four' },
    ],
    answer: 'b',
    explanation: 'five 就是 5，一只小手有五根手指～',
  },
  {
    id: 'low-english-015',
    subject: 'english',
    prompt: '“妈妈”用英语怎么叫？',
    choices: [
      { id: 'a', text: 'mom（妈妈）' },
      { id: 'b', text: 'dad（爸爸）' },
      { id: 'c', text: 'baby（宝宝）' },
    ],
    answer: 'a',
    explanation: 'mom 就是妈妈，最爱你的人～',
  },
  {
    id: 'low-english-016',
    subject: 'english',
    prompt: '“爸爸”用英语怎么叫？',
    choices: [
      { id: 'a', text: 'mom（妈妈）' },
      { id: 'b', text: 'dad（爸爸）' },
    ],
    answer: 'b',
    explanation: 'dad 就是爸爸～',
  },
  {
    id: 'low-english-017',
    subject: 'english',
    prompt: '“鸟”用英语怎么说？（会飞的小动物）',
    choices: [
      { id: 'a', text: 'bird（鸟）' },
      { id: 'b', text: 'fish（鱼）' },
      { id: 'c', text: 'cat（猫）' },
    ],
    answer: 'a',
    explanation: 'bird 就是小鸟，叽叽喳喳飞呀飞～',
  },
  {
    id: 'low-english-018',
    subject: 'english',
    prompt: '黑色用英语怎么说？（晚上天黑黑的颜色）',
    choices: [
      { id: 'a', text: 'white（白色）' },
      { id: 'b', text: 'black（黑色）' },
      { id: 'c', text: 'yellow（黄色）' },
    ],
    answer: 'b',
    explanation: 'black 是黑色，像晚上的天空～',
  },
  {
    id: 'low-english-019',
    subject: 'english',
    prompt: '字母表里最开始的第一个字母是哪个？',
    choices: [
      { id: 'a', text: 'A' },
      { id: 'b', text: 'Z' },
      { id: 'c', text: 'M' },
    ],
    answer: 'a',
    explanation: 'A 是第一个字母，唱歌就从 A 开始～',
  },
  {
    id: 'low-english-020',
    subject: 'english',
    prompt: '数字“2”用英语怎么说？',
    choices: [
      { id: 'a', text: 'two' },
      { id: 'b', text: 'three' },
      { id: 'c', text: 'one' },
    ],
    answer: 'a',
    explanation: 'two 就是 2，两只小眼睛～',
  },
  {
    id: 'low-english-021',
    subject: 'english',
    prompt: '“鱼”用英语怎么说？（在水里游的）',
    choices: [
      { id: 'a', text: 'bird（鸟）' },
      { id: 'b', text: 'fish（鱼）' },
      { id: 'c', text: 'dog（狗）' },
    ],
    answer: 'b',
    explanation: 'fish 就是小鱼，在水里游来游去～',
  },
  {
    id: 'low-english-022',
    subject: 'english',
    prompt: '白色用英语怎么说？（像云朵和雪一样）',
    choices: [
      { id: 'a', text: 'white（白色）' },
      { id: 'b', text: 'black（黑色）' },
      { id: 'c', text: 'blue（蓝色）' },
    ],
    answer: 'a',
    explanation: 'white 是白色，像白云和雪花～',
  },
]
