import type { BattleQuestion } from '../core'

// 英语 · 高年级（六年级，约11-13岁，给闫一依）
// 词义、简单语法、日常表达、单复数。稍有深度、更机灵、口语化。
export const items: BattleQuestion[] = [
  {
    id: 'high-english-001',
    subject: 'english',
    prompt: '“delicious”是什么意思？',
    choices: [
      { id: 'a', text: '危险的' },
      { id: 'b', text: '好吃的' },
      { id: 'c', text: '安静的' },
    ],
    answer: 'b',
    explanation: 'delicious = 美味的、好吃的，夸饭好吃就用它。',
  },
  {
    id: 'high-english-002',
    subject: 'english',
    prompt: '一只猫是 cat，那么三只猫怎么写？',
    choices: [
      { id: 'a', text: 'cats' },
      { id: 'b', text: 'cat' },
      { id: 'c', text: 'cates' },
    ],
    answer: 'a',
    explanation: '大多数名词变复数直接加 s，three cats。',
  },
  {
    id: 'high-english-003',
    subject: 'english',
    prompt: '别人对你说 “Thank you!”，最自然的回答是？',
    choices: [
      { id: 'a', text: "You're welcome." },
      { id: 'b', text: 'Goodbye.' },
      { id: 'c', text: 'I am fine.' },
    ],
    answer: 'a',
    explanation: '“不客气”就是 You\'re welcome。',
  },
  {
    id: 'high-english-004',
    subject: 'english',
    prompt: '下面哪个是 “happy” 的反义词？',
    choices: [
      { id: 'a', text: 'tall' },
      { id: 'b', text: 'sad' },
      { id: 'c', text: 'fast' },
    ],
    answer: 'b',
    explanation: 'happy 开心 ↔ sad 难过。',
  },
  {
    id: 'high-english-005',
    subject: 'english',
    prompt: '“She ___ to school every day.” 横线上填哪个？',
    choices: [
      { id: 'a', text: 'go' },
      { id: 'b', text: 'goes' },
      { id: 'c', text: 'going' },
    ],
    answer: 'b',
    explanation: '主语是 she（第三人称单数），一般现在时动词要加 es，goes。',
  },
  {
    id: 'high-english-006',
    subject: 'english',
    prompt: '“Monday” 是星期几？',
    choices: [
      { id: 'a', text: '星期一' },
      { id: 'b', text: '星期天' },
      { id: 'c', text: '星期五' },
    ],
    answer: 'a',
    explanation: 'Monday = 星期一，一周的开头。',
  },
  {
    id: 'high-english-007',
    subject: 'english',
    prompt: '下面哪个单词的复数形式是不规则的？',
    choices: [
      { id: 'a', text: 'dog（dogs）' },
      { id: 'b', text: 'child（children）' },
      { id: 'c', text: 'book（books）' },
    ],
    answer: 'b',
    explanation: 'child 的复数是 children，不是加 s，属于不规则变化。',
  },
  {
    id: 'high-english-008',
    subject: 'english',
    prompt: '问别人“现在几点了”，应该说？',
    choices: [
      { id: 'a', text: 'How old are you?' },
      { id: 'b', text: "What's the time?" },
      { id: 'c', text: 'Where are you?' },
    ],
    answer: 'b',
    explanation: "What's the time?（或 What time is it?）= 现在几点了。",
  },
  {
    id: 'high-english-009',
    subject: 'english',
    prompt: '“This is ___ apple.” 横线上填哪个最对？',
    choices: [
      { id: 'a', text: 'a' },
      { id: 'b', text: 'an' },
      { id: 'c', text: 'the' },
    ],
    answer: 'b',
    explanation: 'apple 以元音音开头，前面用 an，an apple。',
  },
  {
    id: 'high-english-010',
    subject: 'english',
    prompt: '“weather” 这个词说的是什么？',
    choices: [
      { id: 'a', text: '天气' },
      { id: 'b', text: '星期' },
      { id: 'c', text: '作业' },
    ],
    answer: 'a',
    explanation: 'weather = 天气，注意别和 whether（是否）搞混。',
  },
  {
    id: 'high-english-011',
    subject: 'english',
    prompt: '“I ___ a student.” 横线上填哪个 be 动词？',
    choices: [
      { id: 'a', text: 'is' },
      { id: 'b', text: 'am' },
      { id: 'c', text: 'are' },
    ],
    answer: 'b',
    explanation: 'I 后面的 be 动词永远用 am。',
  },
  {
    id: 'high-english-012',
    subject: 'english',
    prompt: '比较级：“tall” 变成“更高”怎么写？',
    choices: [
      { id: 'a', text: 'taller' },
      { id: 'b', text: 'tallest' },
      { id: 'c', text: 'more tall' },
    ],
    answer: 'a',
    explanation: '短词比较级直接加 er，taller = 更高。',
  },
  {
    id: 'high-english-013',
    subject: 'english',
    prompt: '“favorite” 是什么意思？',
    choices: [
      { id: 'a', text: '害怕的' },
      { id: 'b', text: '最喜欢的' },
      { id: 'c', text: '免费的' },
    ],
    answer: 'b',
    explanation: 'favorite = 最爱的、最喜欢的，my favorite color 我最喜欢的颜色。',
  },
  {
    id: 'high-english-014',
    subject: 'english',
    prompt: '别人问 “How are you?”，下面哪个回答最合适？',
    choices: [
      { id: 'a', text: 'I am eleven.' },
      { id: 'b', text: "I'm fine, thank you." },
      { id: 'c', text: 'It is Monday.' },
    ],
    answer: 'b',
    explanation: '问“你好吗”，回答 I\'m fine, thank you. 最稳。',
  },
  {
    id: 'high-english-015',
    subject: 'english',
    prompt: '“There ___ two books on the desk.” 横线上填哪个？',
    choices: [
      { id: 'a', text: 'is' },
      { id: 'b', text: 'are' },
      { id: 'c', text: 'am' },
    ],
    answer: 'b',
    explanation: 'two books 是复数，所以用 there are。',
  },
  {
    id: 'high-english-016',
    subject: 'english',
    prompt: '下面哪个单词是“蔬菜”的意思？',
    choices: [
      { id: 'a', text: 'vegetable' },
      { id: 'b', text: 'animal' },
      { id: 'c', text: 'building' },
    ],
    answer: 'a',
    explanation: 'vegetable = 蔬菜；animal 动物，building 建筑物。',
  },
  {
    id: 'high-english-017',
    subject: 'english',
    prompt: '过去式：“go” 的过去式是哪个？',
    choices: [
      { id: 'a', text: 'goed' },
      { id: 'b', text: 'went' },
      { id: 'c', text: 'gone' },
    ],
    answer: 'b',
    explanation: 'go 是不规则动词，过去式是 went。',
  },
  {
    id: 'high-english-018',
    subject: 'english',
    prompt: '想表达“我喜欢打篮球”，下面哪句对？',
    choices: [
      { id: 'a', text: 'I like playing basketball.' },
      { id: 'b', text: 'I like play basketball.' },
      { id: 'c', text: 'I likes basketball play.' },
    ],
    answer: 'a',
    explanation: 'like 后面接动词时用 doing 形式：like playing basketball。',
  },
  {
    id: 'high-english-019',
    subject: 'english',
    prompt: '“This is my book. ___ book is over there.” 指别人的书，填哪个？',
    choices: [
      { id: 'a', text: 'My' },
      { id: 'b', text: 'His' },
      { id: 'c', text: 'Me' },
    ],
    answer: 'b',
    explanation: 'His = 他的，His book 他的书；my 是我的，me 是宾格。',
  },
  {
    id: 'high-english-020',
    subject: 'english',
    prompt: '“difficult” 是什么意思？',
    choices: [
      { id: 'a', text: '简单的' },
      { id: 'b', text: '困难的' },
      { id: 'c', text: '安静的' },
    ],
    answer: 'b',
    explanation: 'difficult = 困难的、难的，反义词是 easy。',
  },
  {
    id: 'high-english-021',
    subject: 'english',
    prompt: '想约朋友“我们一起去吧”，哪句最自然？',
    choices: [
      { id: 'a', text: "Let's go together!" },
      { id: 'b', text: 'Go you me!' },
      { id: 'c', text: 'We go is together.' },
    ],
    answer: 'a',
    explanation: "Let's go together! = 我们一起走吧，Let's = let us。",
  },
  {
    id: 'high-english-022',
    subject: 'english',
    prompt: '“Do you have ___ pens?” 问“有没有一些钢笔”，填哪个？',
    choices: [
      { id: 'a', text: 'some' },
      { id: 'b', text: 'any' },
      { id: 'c', text: 'a' },
    ],
    answer: 'b',
    explanation: '疑问句、否定句里一般用 any；some 多用于肯定句。',
  },
]
