import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'low-funny-001',
    subject: 'funny',
    prompt: '什么东西越洗越脏？',
    choices: [
      { id: 'a', text: '小手' },
      { id: 'b', text: '水' },
      { id: 'c', text: '袜子' },
    ],
    answer: 'b',
    explanation: '洗东西的水越用越脏啦！',
  },
  {
    id: 'low-funny-002',
    subject: 'funny',
    prompt: '小白加小白等于什么？（猜一句话）',
    choices: [
      { id: 'a', text: '小白兔（小白兔=小白two）' },
      { id: 'b', text: '两只白猫' },
      { id: 'c', text: '一片白云' },
    ],
    answer: 'a',
    explanation: '两个小白，就是“小白 two”，听起来像“小白兔”！',
  },
  {
    id: 'low-funny-003',
    subject: 'funny',
    prompt: '什么动物最爱贴在墙上？',
    choices: [
      { id: 'a', text: '小狗' },
      { id: 'b', text: '壁虎' },
      { id: 'c', text: '小鱼' },
    ],
    answer: 'b',
    explanation: '壁虎的“壁”就是墙壁，它最会爬墙啦！',
  },
  {
    id: 'low-funny-004',
    subject: 'funny',
    prompt: '什么帽子永远戴不到头上？',
    choices: [
      { id: 'a', text: '草帽' },
      { id: 'b', text: '瓶盖（瓶子的帽子）' },
      { id: 'c', text: '棉帽' },
    ],
    answer: 'b',
    explanation: '瓶盖是瓶子的“帽子”，可没法戴到头上哦！',
  },
  {
    id: 'low-funny-005',
    subject: 'funny',
    prompt: '什么时候太阳会从西边出来？',
    choices: [
      { id: 'a', text: '下雨天' },
      { id: 'b', text: '做梦的时候' },
      { id: 'c', text: '过生日' },
    ],
    answer: 'b',
    explanation: '只有在梦里，太阳才会从西边出来呀！',
  },
  {
    id: 'low-funny-006',
    subject: 'funny',
    prompt: '一只小鸟站在树上，为什么不会掉下来？',
    choices: [
      { id: 'a', text: '它睡着了' },
      { id: 'b', text: '它会抓紧树枝' },
      { id: 'c', text: '它没有重量' },
    ],
    answer: 'b',
    explanation: '小鸟用小爪子紧紧抓住树枝，就不会掉啦！',
  },
  {
    id: 'low-funny-007',
    subject: 'funny',
    prompt: '什么东西有嘴巴，却不会说话？',
    choices: [
      { id: 'a', text: '茶杯（杯口叫“杯嘴”）' },
      { id: 'b', text: '小狗' },
      { id: 'c', text: '电视' },
    ],
    answer: 'a',
    explanation: '杯子有“嘴”，可它一句话也不会说！',
  },
  {
    id: 'low-funny-008',
    subject: 'funny',
    prompt: '什么车没有轮子？',
    choices: [
      { id: 'a', text: '小汽车' },
      { id: 'b', text: '风车' },
      { id: 'c', text: '自行车' },
    ],
    answer: 'b',
    explanation: '风车靠风转圈圈，可没有轮子哦！',
  },
  {
    id: 'low-funny-009',
    subject: 'funny',
    prompt: '小明往左走，影子往哪走？',
    choices: [
      { id: 'a', text: '往右走' },
      { id: 'b', text: '跟着一起走' },
      { id: 'c', text: '飞到天上' },
    ],
    answer: 'b',
    explanation: '影子是个跟屁虫，你走哪它走哪！',
  },
  {
    id: 'low-funny-010',
    subject: 'funny',
    prompt: '什么水果最爱生气？',
    choices: [
      { id: 'a', text: '芒果' },
      { id: 'b', text: '火龙果（带“火”）' },
      { id: 'c', text: '香蕉' },
    ],
    answer: 'b',
    explanation: '火龙果名字里有个“火”，好像在发火气呢！',
  },
  {
    id: 'low-funny-011',
    subject: 'funny',
    prompt: '冰化了以后会变成什么？',
    choices: [
      { id: 'a', text: '水' },
      { id: 'b', text: '糖' },
      { id: 'c', text: '云' },
    ],
    answer: 'a',
    explanation: '冰块一化就变成水啦！',
  },
  {
    id: 'low-funny-012',
    subject: 'funny',
    prompt: '什么东西越多越冷？',
    choices: [
      { id: 'a', text: '太阳' },
      { id: 'b', text: '雪' },
      { id: 'c', text: '火' },
    ],
    answer: 'b',
    explanation: '雪下得越多，天气就越冷啦！',
  },
  {
    id: 'low-funny-013',
    subject: 'funny',
    prompt: '小猫为什么喜欢抓老鼠？',
    choices: [
      { id: 'a', text: '想跟它玩游戏' },
      { id: 'b', text: '因为爱吃老鼠' },
      { id: 'c', text: '老鼠欠它钱' },
    ],
    answer: 'b',
    explanation: '小猫最爱抓老鼠当点心吃啦！',
  },
  {
    id: 'low-funny-014',
    subject: 'funny',
    prompt: '什么门永远关不上？',
    choices: [
      { id: 'a', text: '大铁门' },
      { id: 'b', text: '球门' },
      { id: 'c', text: '木头门' },
    ],
    answer: 'b',
    explanation: '足球的球门是空的，关也关不上呀！',
  },
  {
    id: 'low-funny-015',
    subject: 'funny',
    prompt: '什么东西天黑才出来，天亮就不见了？',
    choices: [
      { id: 'a', text: '月亮和星星' },
      { id: 'b', text: '太阳' },
      { id: 'c', text: '彩虹' },
    ],
    answer: 'a',
    explanation: '月亮星星只在晚上出来，天一亮就躲起来啦！',
  },
  {
    id: 'low-funny-016',
    subject: 'funny',
    prompt: '大象用什么洗澡？',
    choices: [
      { id: 'a', text: '毛巾' },
      { id: 'b', text: '长长的鼻子喷水' },
      { id: 'c', text: '小勺子' },
    ],
    answer: 'b',
    explanation: '大象用长鼻子吸水，再喷到身上洗澡！',
  },
  {
    id: 'low-funny-017',
    subject: 'funny',
    prompt: '什么东西你有，别人也有，但不能借给别人？',
    choices: [
      { id: 'a', text: '铅笔' },
      { id: 'b', text: '名字' },
      { id: 'c', text: '橡皮' },
    ],
    answer: 'b',
    explanation: '每个人都有名字，可名字是借不走的哦！',
  },
  {
    id: 'low-funny-018',
    subject: 'funny',
    prompt: '一个人掉进河里，为什么头发没湿？',
    choices: [
      { id: 'a', text: '他游得快' },
      { id: 'b', text: '他是光头' },
      { id: 'c', text: '河里没有水' },
    ],
    answer: 'b',
    explanation: '光头没有头发，当然不会湿啦！',
  },
  {
    id: 'low-funny-019',
    subject: 'funny',
    prompt: '什么东西人人都想要，可拿到手就没了？',
    choices: [
      { id: 'a', text: '糖果' },
      { id: 'b', text: '影子' },
      { id: 'c', text: '泡泡' },
    ],
    answer: 'c',
    explanation: '泡泡一碰就破，想抓也抓不住！',
  },
  {
    id: 'low-funny-020',
    subject: 'funny',
    prompt: '青蛙为什么会跳？',
    choices: [
      { id: 'a', text: '因为它腿很有力' },
      { id: 'b', text: '因为它怕痒' },
      { id: 'c', text: '因为它在跳舞' },
    ],
    answer: 'a',
    explanation: '青蛙的后腿很有劲，一蹬就跳得老远！',
  },
  {
    id: 'low-funny-021',
    subject: 'funny',
    prompt: '什么东西早上四条腿可以坐，你天天都坐它？',
    choices: [
      { id: 'a', text: '小椅子' },
      { id: 'b', text: '小狗' },
      { id: 'c', text: '皮球' },
    ],
    answer: 'a',
    explanation: '小椅子有四条腿，每天都给你坐！',
  },
  {
    id: 'low-funny-022',
    subject: 'funny',
    prompt: '什么笔不能写字？',
    choices: [
      { id: 'a', text: '铅笔' },
      { id: 'b', text: '油画笔' },
      { id: 'c', text: '鼻（鼻子，和“笔”同音）' },
    ],
    answer: 'c',
    explanation: '“鼻”和“笔”读音很像，可鼻子怎么写字呀！',
  },
]
