import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'high-funny-001',
    subject: 'funny',
    prompt: '一个人走在沙漠里，背上背了个大包，为什么死了？',
    choices: [
      { id: 'a', text: '渴死了' },
      { id: 'b', text: '降落伞没打开' },
      { id: 'c', text: '中暑了' },
    ],
    answer: 'b',
    explanation: '那个大包其实是没打开的降落伞，他是摔下来的。',
  },
  {
    id: 'high-funny-002',
    subject: 'funny',
    prompt: '什么车永远不需要加油也不需要充电，却能一直跑？',
    choices: [
      { id: 'a', text: '玩具车' },
      { id: 'b', text: '风车' },
      { id: 'c', text: '碰碰车' },
    ],
    answer: 'b',
    explanation: '风车靠风转，根本不烧油也不用电。',
  },
  {
    id: 'high-funny-003',
    subject: 'funny',
    prompt: '考试时同桌问你借橡皮，你借了，但是他成绩反而比你高，为什么？',
    choices: [
      { id: 'a', text: '他本来就比你聪明' },
      { id: 'b', text: '橡皮把你的好答案擦掉了' },
      { id: 'c', text: '这道题没有标准答案' },
    ],
    answer: 'a',
    explanation: '别想太多，橡皮跟成绩没关系——这是个故意带歪你的脑筋急转弯。',
  },
  {
    id: 'high-funny-004',
    subject: 'funny',
    prompt: '什么字大家看了都念错？',
    choices: [
      { id: 'a', text: '错' },
      { id: 'b', text: '对' },
      { id: 'c', text: '念' },
    ],
    answer: 'a',
    explanation: '题目说"念错"，那个字就是"错"字本身。',
  },
  {
    id: 'high-funny-005',
    subject: 'funny',
    prompt: '一个数学老师丢了一只猫，他在黑板上写了什么寻猫启事？',
    choices: [
      { id: 'a', text: '求一只猫的解' },
      { id: 'b', text: '已知一只猫，求猫' },
      { id: 'c', text: '设这只猫为 X' },
    ],
    answer: 'c',
    explanation: '数学老师当然把走丢的未知猫设成 X 啦。',
  },
  {
    id: 'high-funny-006',
    subject: 'funny',
    prompt: '冰箱里放了一只大象，怎么才能再放进一只长颈鹿？',
    choices: [
      { id: 'a', text: '先把大象拿出来' },
      { id: 'b', text: '把冰箱换大一点' },
      { id: 'c', text: '把长颈鹿折起来' },
    ],
    answer: 'a',
    explanation: '经典连环问：要放长颈鹿，得先把大象请出来。',
  },
  {
    id: 'high-funny-007',
    subject: 'funny',
    prompt: '什么东西你一说出它的名字，它就立刻消失了？',
    choices: [
      { id: 'a', text: '影子' },
      { id: 'b', text: '安静' },
      { id: 'c', text: '泡泡' },
    ],
    answer: 'b',
    explanation: '你一开口说"安静"，安静就被你打破了。',
  },
  {
    id: 'high-funny-008',
    subject: 'funny',
    prompt: '小明把一张纸对折，能对折多少次后厚度超过他的身高？',
    choices: [
      { id: 'a', text: '大约 100 次' },
      { id: 'b', text: '其实折几次手就折不动了' },
      { id: 'c', text: '永远折不到' },
    ],
    answer: 'b',
    explanation: '理论上 7 次左右厚度就翻很多倍，但普通纸对折六七次手就折不动了，根本到不了身高。',
  },
  {
    id: 'high-funny-009',
    subject: 'funny',
    prompt: '什么情况下，1 加 1 不等于 2？',
    choices: [
      { id: 'a', text: '永远等于 2' },
      { id: 'b', text: '算错的时候' },
      { id: 'c', text: '一堆沙加一堆沙，还是一堆' },
    ],
    answer: 'c',
    explanation: '一堆沙倒进另一堆沙，合起来还是"一堆"，所以 1 堆 + 1 堆 = 1 堆。',
  },
  {
    id: 'high-funny-010',
    subject: 'funny',
    prompt: '一座桥写着"限重 5 吨"，一辆 4 吨的卡车正好开到桥中间，这时一只 1 公斤的小鸟落在车顶，桥会塌吗？',
    choices: [
      { id: 'a', text: '会，正好超重了' },
      { id: 'b', text: '不会，差得远呢' },
      { id: 'c', text: '会，因为小鸟很重' },
    ],
    answer: 'b',
    explanation: '4 吨加 1 公斤离 5 吨还差着将近 1 吨，小鸟那点重量根本不算啥。',
  },
  {
    id: 'high-funny-011',
    subject: 'funny',
    prompt: '什么东西明明是你的，但别人用得比你多？',
    choices: [
      { id: 'a', text: '你的名字' },
      { id: 'b', text: '你的橡皮' },
      { id: 'c', text: '你的书包' },
    ],
    answer: 'a',
    explanation: '你的名字是你的，可平时都是别人在叫你、在用它。',
  },
  {
    id: 'high-funny-012',
    subject: 'funny',
    prompt: '钟表店里所有的钟都停了，可老板说生意照样很好，为什么？',
    choices: [
      { id: 'a', text: '大家来买不会停的钟' },
      { id: 'b', text: '停了的钟一天也能准两次' },
      { id: 'c', text: '老板在吹牛' },
    ],
    answer: 'a',
    explanation: '钟都停了说明它们都坏了，大家正好来买新的、能走的钟，所以生意好。',
  },
  {
    id: 'high-funny-013',
    subject: 'funny',
    prompt: '小红把同一道题做了三遍，每遍答案都不一样，老师却给了满分，为什么？',
    choices: [
      { id: 'a', text: '老师没看仔细' },
      { id: 'b', text: '那是一道开放题，答案不止一个' },
      { id: 'c', text: '老师很喜欢小红' },
    ],
    answer: 'b',
    explanation: '开放性题目本来就允许多种答案，三个都对当然满分。',
  },
  {
    id: 'high-funny-014',
    subject: 'funny',
    prompt: '一个房间里有 10 根蜡烛，风吹灭了 3 根，过一会儿又吹灭了 2 根，最后房间里还剩几根蜡烛？',
    choices: [
      { id: 'a', text: '5 根' },
      { id: 'b', text: '10 根' },
      { id: 'c', text: '5 根，灭的烧没了' },
    ],
    answer: 'b',
    explanation: '蜡烛被吹灭只是不亮了，又没消失，房间里还是 10 根。',
  },
  {
    id: 'high-funny-015',
    subject: 'funny',
    prompt: '什么东西，越往里走越往外？',
    choices: [
      { id: 'a', text: '隧道' },
      { id: 'b', text: '迷宫' },
      { id: 'c', text: '螺丝（往里拧就往里走，往外拧就出来）' },
    ],
    answer: 'a',
    explanation: '隧道走到一半之后，越往前走其实就越接近出口、越往"外"了。',
  },
  {
    id: 'high-funny-016',
    subject: 'funny',
    prompt: '一个班 30 个同学，每人和其他每个人都握一次手，老师却说一共握了不到 30 次，可能吗？',
    choices: [
      { id: 'a', text: '不可能，肯定超过 30 次' },
      { id: 'b', text: '可能，老师在开玩笑' },
      { id: 'c', text: '可能，只数了自己的' },
    ],
    answer: 'a',
    explanation: '30 个人两两握手要 435 次，远超 30，老师这话明显不对——别被绕进去。',
  },
  {
    id: 'high-funny-017',
    subject: 'funny',
    prompt: '什么字，去掉一半还是它自己？',
    choices: [
      { id: 'a', text: '半' },
      { id: 'b', text: '田' },
      { id: 'c', text: '日' },
    ],
    answer: 'a',
    explanation: '"半"这个字，意思就是去掉一半——它本身就在说自己。',
  },
  {
    id: 'high-funny-018',
    subject: 'funny',
    prompt: '小华倒着把日历从 12 月看到 1 月，他发现一年里最短的月份是哪个？',
    choices: [
      { id: 'a', text: '二月' },
      { id: 'b', text: '十二月' },
      { id: 'c', text: '怎么看都是二月' },
    ],
    answer: 'c',
    explanation: '不管正着看还是倒着看，二月天数最少，永远是最短的那个月。',
  },
  {
    id: 'high-funny-019',
    subject: 'funny',
    prompt: '什么东西，你越分给别人，自己反而越多？',
    choices: [
      { id: 'a', text: '零食' },
      { id: 'b', text: '快乐' },
      { id: 'c', text: '零花钱' },
    ],
    answer: 'b',
    explanation: '快乐分享给别人，自己不但不会少，反而会更开心。',
  },
  {
    id: 'high-funny-020',
    subject: 'funny',
    prompt: '一只蜗牛要爬 10 米高的井，白天爬 3 米，晚上滑下 2 米，它第几天能爬出井口？',
    choices: [
      { id: 'a', text: '第 10 天' },
      { id: 'b', text: '第 8 天' },
      { id: 'c', text: '永远爬不出来' },
    ],
    answer: 'b',
    explanation: '每天净爬 1 米，第 7 天结束在 7 米，第 8 天白天爬 3 米正好到 10 米爬出去了，不会再滑下来。',
  },
  {
    id: 'high-funny-021',
    subject: 'funny',
    prompt: '什么问题，不管你怎么回答都是错的？',
    choices: [
      { id: 'a', text: '"你睡着了吗？"' },
      { id: 'b', text: '"你叫什么名字？"' },
      { id: 'c', text: '"现在几点了？"' },
    ],
    answer: 'a',
    explanation: '真睡着了你根本没法回答；能开口答"睡着了"，那就说明你没睡——怎么答都不对。',
  },
  {
    id: 'high-funny-022',
    subject: 'funny',
    prompt: '老师说："谁能用一句话让我又哭又笑？" 哪个回答最可能成功？',
    choices: [
      { id: 'a', text: '"老师，您今天真好看。"' },
      { id: 'b', text: '"老师，我帮您把作业全改完了……改错了。"' },
      { id: 'c', text: '"老师，下课了。"' },
    ],
    answer: 'b',
    explanation: '听到有人帮忙改作业先笑了，再听说全改错了又想哭，一句话同时戳中两种情绪。',
  },
]
