import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'low-interest-001',
    subject: 'interest',
    prompt: '小猪佩奇最喜欢做的一件事是什么？',
    choices: [
      { id: 'a', text: '跳泥坑' },
      { id: 'b', text: '爬大树' },
      { id: 'c', text: '钓大鱼' },
    ],
    answer: 'a',
    explanation: '佩奇和弟弟乔治最爱穿着雨靴跳泥坑啦。',
  },
  {
    id: 'low-interest-002',
    subject: 'interest',
    prompt: '汪汪队里负责开警车、戴蓝帽子的是哪只小狗？',
    choices: [
      { id: 'a', text: '毛毛' },
      { id: 'b', text: '阿奇' },
      { id: 'c', text: '天天' },
    ],
    answer: 'b',
    explanation: '阿奇是警犬，开着警车帮大家解决问题。',
  },
  {
    id: 'low-interest-003',
    subject: 'interest',
    prompt: '玩积木的时候，下面哪种搭法最容易倒？',
    choices: [
      { id: 'a', text: '大块在下面，小块在上面' },
      { id: 'b', text: '小块在下面，大块压上面' },
      { id: 'c', text: '一块一块平平地铺开' },
    ],
    answer: 'b',
    explanation: '下小上大头重脚轻，轻轻一碰就倒啦。',
  },
  {
    id: 'low-interest-004',
    subject: 'interest',
    prompt: '踢足球的时候，球进了哪里才算得分？',
    choices: [
      { id: 'a', text: '踢进球门' },
      { id: 'b', text: '踢出场外' },
      { id: 'c', text: '踢到天上' },
    ],
    answer: 'a',
    explanation: '把球踢进对方的球门就得一分。',
  },
  {
    id: 'low-interest-005',
    subject: 'interest',
    prompt: '玩跳绳，绳子转一圈，脚要怎么做？',
    choices: [
      { id: 'a', text: '一直站着不动' },
      { id: 'b', text: '在绳子过来时往上跳一下' },
      { id: 'c', text: '坐到地上' },
    ],
    answer: 'b',
    explanation: '绳子到脚边时轻轻一跳，就跳过去啦。',
  },
  {
    id: 'low-interest-006',
    subject: 'interest',
    prompt: '画太阳的时候，太阳一般涂成什么颜色？',
    choices: [
      { id: 'a', text: '黑色' },
      { id: 'b', text: '黄色或红色' },
      { id: 'c', text: '绿色' },
    ],
    answer: 'b',
    explanation: '太阳暖暖的，小朋友常画成黄色或红色。',
  },
  {
    id: 'low-interest-007',
    subject: 'interest',
    prompt: '搭乐高最后多出来一两块小零件，应该怎么办最好？',
    choices: [
      { id: 'a', text: '收进盒子里别弄丢' },
      { id: 'b', text: '扔进垃圾桶' },
      { id: 'c', text: '吃进肚子里' },
    ],
    answer: 'a',
    explanation: '小零件要收好，别丢了也千万别放进嘴里。',
  },
  {
    id: 'low-interest-008',
    subject: 'interest',
    prompt: '奥特曼一般是用来做什么的英雄？',
    choices: [
      { id: 'a', text: '打怪兽、保护大家' },
      { id: 'b', text: '做饭给大家吃' },
      { id: 'c', text: '专门捣乱' },
    ],
    answer: 'a',
    explanation: '奥特曼是变大打怪兽、保护城市的英雄。',
  },
  {
    id: 'low-interest-009',
    subject: 'interest',
    prompt: '骑自行车想停下来，应该怎么做？',
    choices: [
      { id: 'a', text: '使劲蹬得更快' },
      { id: 'b', text: '捏刹车，慢慢停' },
      { id: 'c', text: '闭上眼睛松手' },
    ],
    answer: 'b',
    explanation: '轻轻捏住刹车，车子就会慢慢停下。',
  },
  {
    id: 'low-interest-010',
    subject: 'interest',
    prompt: '玩橡皮泥，想做一个圆圆的球，要怎么做？',
    choices: [
      { id: 'a', text: '用两只手把它搓圆' },
      { id: 'b', text: '用力压扁' },
      { id: 'c', text: '撕成一小条一小条' },
    ],
    answer: 'a',
    explanation: '把橡皮泥放手心里转着搓，就变成小球啦。',
  },
  {
    id: 'low-interest-011',
    subject: 'interest',
    prompt: '小朋友很喜欢的“滑滑梯”，玩的时候应该怎么滑？',
    choices: [
      { id: 'a', text: '从上面坐着往下滑' },
      { id: 'b', text: '从下往上倒着爬' },
      { id: 'c', text: '站在最高处往下跳' },
    ],
    answer: 'a',
    explanation: '坐好从上往下滑才安全又好玩。',
  },
  {
    id: 'low-interest-012',
    subject: 'interest',
    prompt: '游泳的时候，下面哪样东西能帮我们浮起来？',
    choices: [
      { id: 'a', text: '游泳圈' },
      { id: 'b', text: '大石头' },
      { id: 'c', text: '铁锅' },
    ],
    answer: 'a',
    explanation: '游泳圈里有空气，能把我们托在水面上。',
  },
  {
    id: 'low-interest-013',
    subject: 'interest',
    prompt: '吹泡泡的时候，应该怎么吹泡泡才会变大？',
    choices: [
      { id: 'a', text: '又轻又慢地吹气' },
      { id: 'b', text: '一下子用力猛吹' },
      { id: 'c', text: '把泡泡水喝掉' },
    ],
    answer: 'a',
    explanation: '轻轻慢慢吹，泡泡才会越来越大不会破。',
  },
  {
    id: 'low-interest-014',
    subject: 'interest',
    prompt: '小朋友很喜欢的“捉迷藏”，当“鬼”的人要做什么？',
    choices: [
      { id: 'a', text: '去找躲起来的人' },
      { id: 'b', text: '自己躲起来' },
      { id: 'c', text: '回家睡觉' },
    ],
    answer: 'a',
    explanation: '当鬼的人要数数，然后去把躲起来的小伙伴找出来。',
  },
  {
    id: 'low-interest-015',
    subject: 'interest',
    prompt: '折纸的时候，想折一只小船，第一步通常要怎么做？',
    choices: [
      { id: 'a', text: '把纸对折一下' },
      { id: 'b', text: '把纸揉成一团' },
      { id: 'c', text: '把纸剪成碎片' },
    ],
    answer: 'a',
    explanation: '先把纸对折压平，再一步步折就能折出小船。',
  },
  {
    id: 'low-interest-016',
    subject: 'interest',
    prompt: '唱歌的时候，下面哪种声音听起来最舒服？',
    choices: [
      { id: 'a', text: '又轻又好听的声音' },
      { id: 'b', text: '使劲大喊大叫' },
      { id: 'c', text: '一直跑调乱唱' },
    ],
    answer: 'a',
    explanation: '用好听的声音唱，大家都爱听。',
  },
  {
    id: 'low-interest-017',
    subject: 'interest',
    prompt: '小朋友爱玩的“石头剪刀布”，剪刀会输给谁？',
    choices: [
      { id: 'a', text: '石头' },
      { id: 'b', text: '布' },
      { id: 'c', text: '另一把剪刀' },
    ],
    answer: 'a',
    explanation: '石头能砸坏剪刀，所以剪刀怕石头。',
  },
  {
    id: 'low-interest-018',
    subject: 'interest',
    prompt: '玩拼图的时候，怎样最容易拼好？',
    choices: [
      { id: 'a', text: '先找出四个角和边' },
      { id: 'b', text: '随便往上乱放' },
      { id: 'c', text: '把拼图藏起来' },
    ],
    answer: 'a',
    explanation: '先拼好四边和角，中间就好对上啦。',
  },
  {
    id: 'low-interest-019',
    subject: 'interest',
    prompt: '冬天最适合堆下面哪样东西？',
    choices: [
      { id: 'a', text: '用雪堆雪人' },
      { id: 'b', text: '用沙子堆雪人' },
      { id: 'c', text: '用水堆雪人' },
    ],
    answer: 'a',
    explanation: '雪能捏成团，下雪天才能堆出胖胖的雪人。',
  },
  {
    id: 'low-interest-020',
    subject: 'interest',
    prompt: '玩遥控小汽车，按前进键车子会怎么样？',
    choices: [
      { id: 'a', text: '往前跑' },
      { id: 'b', text: '飞上天' },
      { id: 'c', text: '不动还睡觉' },
    ],
    answer: 'a',
    explanation: '按前进键，小车就会往前开。',
  },
  {
    id: 'low-interest-021',
    subject: 'interest',
    prompt: '小朋友很爱看的“熊出没”里，光头强最想做什么？',
    choices: [
      { id: 'a', text: '砍树' },
      { id: 'b', text: '种花' },
      { id: 'c', text: '画画' },
    ],
    answer: 'a',
    explanation: '光头强老想砍树，熊大熊二就来保护森林。',
  },
  {
    id: 'low-interest-022',
    subject: 'interest',
    prompt: '拍皮球的时候，球碰到地面会怎么样？',
    choices: [
      { id: 'a', text: '弹起来' },
      { id: 'b', text: '陷进地里' },
      { id: 'c', text: '变成方形' },
    ],
    answer: 'a',
    explanation: '皮球软软有弹性，拍到地上就会弹回来。',
  },
]
