import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'high-interest-001',
    subject: 'interest',
    prompt: '《原神》《崩坏：星穹铁道》这类游戏里，玩家抽到角色和武器的玩法一般叫什么？',
    choices: [
      { id: 'a', text: '抽卡（祈愿）' },
      { id: 'b', text: '种菜' },
      { id: 'c', text: '钓鱼' },
    ],
    answer: 'a',
    explanation: '这种用资源随机获得角色的系统就叫抽卡，原神里好听点叫“祈愿”。',
  },
  {
    id: 'high-interest-002',
    subject: 'interest',
    prompt: '《我的世界》里把矿石、木头放进去能合成工具的那个 3×3 格子界面叫什么？',
    choices: [
      { id: 'a', text: '熔炉' },
      { id: 'b', text: '工作台' },
      { id: 'c', text: '箱子' },
    ],
    answer: 'b',
    explanation: '工作台提供 3×3 的合成格，熔炉是用来烧炼的，箱子只能存东西。',
  },
  {
    id: 'high-interest-003',
    subject: 'interest',
    prompt: '篮球比赛里在三分线外投进一个球，能得几分？',
    choices: [
      { id: 'a', text: '2 分' },
      { id: 'b', text: '3 分' },
      { id: 'c', text: '1 分' },
    ],
    answer: 'b',
    explanation: '三分线外命中算 3 分，线内是 2 分，罚球才是 1 分。',
  },
  {
    id: 'high-interest-004',
    subject: 'interest',
    prompt: '玩拼装积木时，要让两块零件“咬”得很牢，关键是什么？',
    choices: [
      { id: 'a', text: '颜色一样' },
      { id: 'b', text: '凸点和凹槽对齐压紧' },
      { id: 'c', text: '零件越大越好' },
    ],
    answer: 'b',
    explanation: '积木靠上面的凸点扣进下面的凹槽来固定，对齐压紧才结实，跟颜色没关系。',
  },
  {
    id: 'high-interest-005',
    subject: 'interest',
    prompt: '羽毛球里把球高高打到对方后场底线，逼对方退后的那一拍，常被叫做什么？',
    choices: [
      { id: 'a', text: '高远球' },
      { id: 'b', text: '搓小球' },
      { id: 'c', text: '发球' },
    ],
    answer: 'a',
    explanation: '高远球又高又远落到底线，能把对手逼到后场；搓小球是吊到网前的小球。',
  },
  {
    id: 'high-interest-006',
    subject: 'interest',
    prompt: '很多手游和电脑游戏里的“FPS”说的是哪个意思？',
    choices: [
      { id: 'a', text: '每秒画面帧数' },
      { id: 'b', text: '游戏价格' },
      { id: 'c', text: '玩家人数' },
    ],
    answer: 'a',
    explanation: 'FPS 指每秒显示多少帧画面，数字越高画面越流畅。',
  },
  {
    id: 'high-interest-007',
    subject: 'interest',
    prompt: '听歌时一首歌里最容易让人跟着唱、反复出现的高潮部分，一般叫什么？',
    choices: [
      { id: 'a', text: '前奏' },
      { id: 'b', text: '副歌' },
      { id: 'c', text: '尾奏' },
    ],
    answer: 'b',
    explanation: '副歌就是那段重复出现、最抓耳的高潮，前奏在开头、尾奏在结尾。',
  },
  {
    id: 'high-interest-008',
    subject: 'interest',
    prompt: '折纸时想折出一只立体的纸鹤，最开始通常要把正方形纸折成什么基础形？',
    choices: [
      { id: 'a', text: '正方基础形（双正方形）' },
      { id: 'b', text: '揉成一团' },
      { id: 'c', text: '卷成筒' },
    ],
    answer: 'a',
    explanation: '纸鹤一般从“正方基础形”开始一步步折出翅膀和头颈，揉团和卷筒都折不成。',
  },
  {
    id: 'high-interest-009',
    subject: 'interest',
    prompt: '足球比赛中，守门员用手接球只能在哪个范围里？',
    choices: [
      { id: 'a', text: '本方禁区内' },
      { id: 'b', text: '整个半场' },
      { id: 'c', text: '随便哪都行' },
    ],
    answer: 'a',
    explanation: '只有在自己的禁区内门将才能用手碰球，出了禁区用手就要犯规。',
  },
  {
    id: 'high-interest-010',
    subject: 'interest',
    prompt: '很多动画和漫画里说的“声优”，指的是做什么的人？',
    choices: [
      { id: 'a', text: '给角色配音的人' },
      { id: 'b', text: '画画的人' },
      { id: 'c', text: '写剧本的人' },
    ],
    answer: 'a',
    explanation: '声优就是配音演员，用声音演活动画角色；画画的叫原画/作画。',
  },
  {
    id: 'high-interest-011',
    subject: 'interest',
    prompt: '玩魔方时，一次能让一个面转 90 度的最小操作单位，通常被称为什么？',
    choices: [
      { id: 'a', text: '一步（一个转动）' },
      { id: 'b', text: '一层贴纸' },
      { id: 'c', text: '一个角块' },
    ],
    answer: 'a',
    explanation: '魔方的解法都用“步数”来数，每转动一个面就是一步。',
  },
  {
    id: 'high-interest-012',
    subject: 'interest',
    prompt: '打乒乓球时，球落到自己台面再弹起、对手没接住，这一分算谁的？',
    choices: [
      { id: 'a', text: '算发球/击球方得分' },
      { id: 'b', text: '算对手得分' },
      { id: 'c', text: '不算分重发' },
    ],
    answer: 'a',
    explanation: '球正常过网落到对方台面、对方没接好，得分的是把球打过去的一方。',
  },
  {
    id: 'high-interest-013',
    subject: 'interest',
    prompt: '不少卡牌和手游里的“SSR”表示什么？',
    choices: [
      { id: 'a', text: '最稀有、最高级的卡' },
      { id: 'b', text: '最便宜的卡' },
      { id: 'c', text: '坏掉的卡' },
    ],
    answer: 'a',
    explanation: 'R、SR、SSR 是稀有度等级，SSR 通常是最稀有最强的那一档。',
  },
  {
    id: 'high-interest-014',
    subject: 'interest',
    prompt: '画画时把红色和黄色调在一起，会得到什么颜色？',
    choices: [
      { id: 'a', text: '橙色' },
      { id: 'b', text: '绿色' },
      { id: 'c', text: '紫色' },
    ],
    answer: 'a',
    explanation: '红加黄出橙，黄加蓝出绿，红加蓝出紫，这是颜料三原色的基本搭配。',
  },
  {
    id: 'high-interest-015',
    subject: 'interest',
    prompt: '滑板上做的最基础、能让人和板一起跳起来的招式，常被叫什么？',
    choices: [
      { id: 'a', text: 'Ollie（豚跳）' },
      { id: 'b', text: '刹车' },
      { id: 'c', text: '坐着滑' },
    ],
    answer: 'a',
    explanation: 'Ollie 是滑板入门必学的弹跳动作，几乎所有花式都从它开始。',
  },
  {
    id: 'high-interest-016',
    subject: 'interest',
    prompt: '看动画时常说的“番剧”里的“一番”，最接近下面哪个意思？',
    choices: [
      { id: 'a', text: '一季（一档连载动画）' },
      { id: 'b', text: '一集' },
      { id: 'c', text: '一个角色' },
    ],
    answer: 'a',
    explanation: '“番”来自日语，指一档/一季连载的动画作品，不是单指一集。',
  },
  {
    id: 'high-interest-017',
    subject: 'interest',
    prompt: '玩团队竞技游戏时常说的“团灭”是什么意思？',
    choices: [
      { id: 'a', text: '一方全队被击败' },
      { id: 'b', text: '游戏崩溃了' },
      { id: 'c', text: '所有人都赢了' },
    ],
    answer: 'a',
    explanation: '团灭就是一整队的人全被打倒，常常会直接决定一波团战的胜负。',
  },
  {
    id: 'high-interest-018',
    subject: 'interest',
    prompt: '做手工想把两张纸牢牢粘住又不想等很久，下面哪种更合适？',
    choices: [
      { id: 'a', text: '固体胶/双面胶' },
      { id: 'b', text: '清水' },
      { id: 'c', text: '橡皮' },
    ],
    answer: 'a',
    explanation: '固体胶或双面胶粘纸又快又牢，清水粘不住，橡皮是用来擦的。',
  },
  {
    id: 'high-interest-019',
    subject: 'interest',
    prompt: '游泳比赛里，趴着、两只手臂同时向前划再分开的泳姿是哪种？',
    choices: [
      { id: 'a', text: '蝶泳' },
      { id: 'b', text: '自由泳' },
      { id: 'c', text: '仰泳' },
    ],
    answer: 'a',
    explanation: '蝶泳双臂同时往前划水、腿像海豚摆动；自由泳是轮流划手，仰泳则是脸朝上。',
  },
  {
    id: 'high-interest-020',
    subject: 'interest',
    prompt: '很多养成、模拟游戏里说的“肝”，玩家口中一般指什么？',
    choices: [
      { id: 'a', text: '花很多时间反复刷' },
      { id: 'b', text: '花钱充值' },
      { id: 'c', text: '退出游戏' },
    ],
    answer: 'a',
    explanation: '“肝”指靠大量时间反复刷资源；靠花钱堆数值那个一般叫“氪”。',
  },
  {
    id: 'high-interest-021',
    subject: 'interest',
    prompt: '弹尤克里里（小吉他）时，左手按住琴弦、右手拨弦，主要是为了得到什么？',
    choices: [
      { id: 'a', text: '不同的音高' },
      { id: 'b', text: '更大的声音' },
      { id: 'c', text: '换个颜色' },
    ],
    answer: 'a',
    explanation: '左手按在不同品位会改变弦的振动长度，从而弹出不同高低的音。',
  },
  {
    id: 'high-interest-022',
    subject: 'interest',
    prompt: '跳绳想连续跳得久又不绊脚，下面哪个习惯最有帮助？',
    choices: [
      { id: 'a', text: '主要用手腕甩绳、轻轻起跳' },
      { id: 'b', text: '整条手臂使劲大甩' },
      { id: 'c', text: '每次都跳得越高越好' },
    ],
    answer: 'a',
    explanation: '靠手腕带绳、起跳别太高最省力也最稳；大甩手臂、跳太高反而容易累和绊到。',
  },
]
