import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'low-life-001',
    subject: 'life',
    prompt: '时钟上短针指着 3，长针指着 12，现在是几点？',
    choices: [
      { id: 'a', text: '12 点' },
      { id: 'b', text: '3 点' },
      { id: 'c', text: '6 点' },
    ],
    answer: 'b',
    explanation: '短针指几就是几点，长针指 12 表示整点，所以是 3 点。',
  },
  {
    id: 'low-life-002',
    subject: 'life',
    prompt: '长针指到 6，短针在 8 和 9 中间，现在大约是几点几分？',
    choices: [
      { id: 'a', text: '8 点半' },
      { id: 'b', text: '6 点整' },
      { id: 'c', text: '9 点整' },
    ],
    answer: 'a',
    explanation: '长针指 6 是 30 分，短针刚过 8，就是 8 点半。',
  },
  {
    id: 'low-life-003',
    subject: 'life',
    prompt: '一个棒棒糖卖 2 块钱，你给阿姨 5 块钱，应该找回几块？',
    choices: [
      { id: 'a', text: '2 块' },
      { id: 'b', text: '3 块' },
      { id: 'c', text: '5 块' },
    ],
    answer: 'b',
    explanation: '5 块减去 2 块，找回 3 块钱。',
  },
  {
    id: 'low-life-004',
    subject: 'life',
    prompt: '下面哪个是最大的钱？',
    choices: [
      { id: 'a', text: '1 块' },
      { id: 'b', text: '5 毛' },
      { id: 'c', text: '10 块' },
    ],
    answer: 'c',
    explanation: '10 块比 1 块和 5 毛都大。',
  },
  {
    id: 'low-life-005',
    subject: 'life',
    prompt: '买东西花了 8 块钱，你有一张 10 块的，够不够付？',
    choices: [
      { id: 'a', text: '够，还能找钱' },
      { id: 'b', text: '不够' },
    ],
    answer: 'a',
    explanation: '10 块比 8 块多，够付，还能找回 2 块。',
  },
  {
    id: 'low-life-006',
    subject: 'life',
    prompt: '过马路的时候，红绿灯是什么颜色才可以走？',
    choices: [
      { id: 'a', text: '红灯' },
      { id: 'b', text: '黄灯' },
      { id: 'c', text: '绿灯' },
    ],
    answer: 'c',
    explanation: '红灯停，绿灯行，绿灯亮了才能走。',
  },
  {
    id: 'low-life-007',
    subject: 'life',
    prompt: '过马路应该走哪里最安全？',
    choices: [
      { id: 'a', text: '斑马线' },
      { id: 'b', text: '马路中间' },
      { id: 'c', text: '哪里近走哪里' },
    ],
    answer: 'a',
    explanation: '过马路要走斑马线，还要先看看左右有没有车。',
  },
  {
    id: 'low-life-008',
    subject: 'life',
    prompt: '明天要上语文、数学和美术课，整理书包应该装什么？',
    choices: [
      { id: 'a', text: '只装语文书' },
      { id: 'b', text: '语文、数学、美术的东西都装好' },
      { id: 'c', text: '装一堆玩具' },
    ],
    answer: 'b',
    explanation: '按明天的课，把每节课要用的东西都准备齐。',
  },
  {
    id: 'low-life-009',
    subject: 'life',
    prompt: '写完作业后，铅笔、橡皮应该放哪儿？',
    choices: [
      { id: 'a', text: '扔在地上' },
      { id: 'b', text: '收进文具盒里' },
      { id: 'c', text: '随便丢在床上' },
    ],
    answer: 'b',
    explanation: '用完的文具放回文具盒，下次好找又整齐。',
  },
  {
    id: 'low-life-010',
    subject: 'life',
    prompt: '玩完积木以后，正确的做法是？',
    choices: [
      { id: 'a', text: '留在地上等别人收' },
      { id: 'b', text: '自己把积木收进盒子' },
    ],
    answer: 'b',
    explanation: '玩具自己玩完自己收好，房间才不会乱。',
  },
  {
    id: 'low-life-011',
    subject: 'life',
    prompt: '脏衣服换下来以后，应该放进哪里？',
    choices: [
      { id: 'a', text: '脏衣篮' },
      { id: 'b', text: '塞回干净的衣柜' },
      { id: 'c', text: '丢在沙发上' },
    ],
    answer: 'a',
    explanation: '脏衣服放进脏衣篮，等着洗，别和干净衣服混在一起。',
  },
  {
    id: 'low-life-012',
    subject: 'life',
    prompt: '吃完的香蕉皮应该扔进哪个垃圾桶？',
    choices: [
      { id: 'a', text: '可回收垃圾' },
      { id: 'b', text: '厨余垃圾（湿垃圾）' },
      { id: 'c', text: '有害垃圾' },
    ],
    answer: 'b',
    explanation: '香蕉皮、剩饭这些会烂掉的，属于厨余（湿）垃圾。',
  },
  {
    id: 'low-life-013',
    subject: 'life',
    prompt: '喝完的塑料矿泉水瓶，应该放进哪个垃圾桶？',
    choices: [
      { id: 'a', text: '可回收垃圾' },
      { id: 'b', text: '厨余垃圾' },
    ],
    answer: 'a',
    explanation: '干净的塑料瓶可以回收再用，放可回收垃圾桶。',
  },
  {
    id: 'low-life-014',
    subject: 'life',
    prompt: '用过的废电池应该扔进哪个垃圾桶？',
    choices: [
      { id: 'a', text: '可回收垃圾' },
      { id: 'b', text: '有害垃圾' },
      { id: 'c', text: '厨余垃圾' },
    ],
    answer: 'b',
    explanation: '废电池里有对环境有害的东西，要放有害垃圾桶。',
  },
  {
    id: 'low-life-015',
    subject: 'life',
    prompt: '外面在下雪，又冷又飘雪花，你出门该穿什么？',
    choices: [
      { id: 'a', text: '短袖和凉鞋' },
      { id: 'b', text: '厚棉袄和帽子' },
      { id: 'c', text: '游泳衣' },
    ],
    answer: 'b',
    explanation: '下雪天很冷，要穿厚棉袄、戴帽子才暖和。',
  },
  {
    id: 'low-life-016',
    subject: 'life',
    prompt: '天上下大雨，出门要带什么才不会淋湿？',
    choices: [
      { id: 'a', text: '雨伞' },
      { id: 'b', text: '太阳镜' },
      { id: 'c', text: '扇子' },
    ],
    answer: 'a',
    explanation: '下雨天带上雨伞或穿雨衣，就不会被淋湿啦。',
  },
  {
    id: 'low-life-017',
    subject: 'life',
    prompt: '夏天太阳很大、很热，最合适穿哪样？',
    choices: [
      { id: 'a', text: '羽绒服' },
      { id: 'b', text: '薄薄的短袖' },
      { id: 'c', text: '厚毛衣' },
    ],
    answer: 'b',
    explanation: '天热就穿薄一点的短袖，凉快又舒服。',
  },
  {
    id: 'low-life-018',
    subject: 'life',
    prompt: '别人帮了你的忙，你应该说什么？',
    choices: [
      { id: 'a', text: '谢谢' },
      { id: 'b', text: '不理他' },
      { id: 'c', text: '走开' },
    ],
    answer: 'a',
    explanation: '别人帮了你要说“谢谢”，这样很有礼貌。',
  },
  {
    id: 'low-life-019',
    subject: 'life',
    prompt: '不小心踩到了别人的脚，应该怎么办？',
    choices: [
      { id: 'a', text: '说“对不起”' },
      { id: 'b', text: '假装没看见' },
      { id: 'c', text: '怪别人挡路' },
    ],
    answer: 'a',
    explanation: '做错了事要主动说“对不起”，这是讲礼貌的好孩子。',
  },
  {
    id: 'low-life-020',
    subject: 'life',
    prompt: '早上见到老师，应该怎么打招呼？',
    choices: [
      { id: 'a', text: '低头快走过去' },
      { id: 'b', text: '说“老师早上好”' },
    ],
    answer: 'b',
    explanation: '见到老师主动问好，说“老师早上好”很有礼貌。',
  },
  {
    id: 'low-life-021',
    subject: 'life',
    prompt: '有陌生人给你糖、说带你去玩，你应该怎么做？',
    choices: [
      { id: 'a', text: '高兴地跟他走' },
      { id: 'b', text: '不要，告诉爸爸妈妈或老师' },
      { id: 'c', text: '把糖吃了再说' },
    ],
    answer: 'b',
    explanation: '不能跟陌生人走，要赶紧告诉爸爸妈妈或老师。',
  },
  {
    id: 'low-life-022',
    subject: 'life',
    prompt: '家里着火了，应该打哪个电话求救？',
    choices: [
      { id: 'a', text: '110' },
      { id: 'b', text: '119' },
      { id: 'c', text: '120' },
    ],
    answer: 'b',
    explanation: '着火了打 119 找消防员叔叔来救火。',
  },
]
