import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'high-life-001',
    subject: 'life',
    prompt: '钟表上时针指在 3 和 4 中间偏一点，分针指向 6，现在是几点？',
    choices: [
      { id: 'a', text: '3 点半' },
      { id: 'b', text: '4 点半' },
      { id: 'c', text: '3 点 06 分' },
    ],
    answer: 'a',
    explanation: '分针指 6 是过了半小时，时针在 3 和 4 中间，所以是 3 点 30 分。',
  },
  {
    id: 'high-life-002',
    subject: 'life',
    prompt: '电影 18:45 开场，路上要花 35 分钟，你最晚几点出门才不迟到？',
    choices: [
      { id: 'a', text: '18:00' },
      { id: 'b', text: '18:10' },
      { id: 'c', text: '18:30' },
    ],
    answer: 'b',
    explanation: '18:45 往前推 35 分钟是 18:10，再晚就赶不上了。',
  },
  {
    id: 'high-life-003',
    subject: 'life',
    prompt: '买了 17 块钱的东西，你递给收银员一张 50 和一个 2 块硬币，应该找回多少？',
    choices: [
      { id: 'a', text: '33 元' },
      { id: 'b', text: '35 元' },
      { id: 'c', text: '43 元' },
    ],
    answer: 'b',
    explanation: '一共付了 52 元，减去 17 元，找回 35 元。多给 2 块是为了凑整找零更方便。',
  },
  {
    id: 'high-life-004',
    subject: 'life',
    prompt: '一支笔 4.5 元，你想买 3 支，付 20 元够吗？能剩多少？',
    choices: [
      { id: 'a', text: '不够' },
      { id: 'b', text: '够，剩 6.5 元' },
      { id: 'c', text: '够，剩 5.5 元' },
    ],
    answer: 'b',
    explanation: '4.5×3=13.5 元，20-13.5=6.5 元。',
  },
  {
    id: 'high-life-005',
    subject: 'life',
    prompt: '过马路时绿灯开始闪烁了，你正站在路边还没下脚，最稳妥的做法是？',
    choices: [
      { id: 'a', text: '赶紧冲过去' },
      { id: 'b', text: '等下一个绿灯' },
      { id: 'c', text: '走到一半停在路中间' },
    ],
    answer: 'b',
    explanation: '绿灯闪烁说明快变红灯了，没下脚就别冒险，等下一轮最安全。',
  },
  {
    id: 'high-life-006',
    subject: 'life',
    prompt: '没有红绿灯的路口要过马路，正确顺序是？',
    choices: [
      { id: 'a', text: '左右都看，确认没车再走' },
      { id: 'b', text: '只看左边就走' },
      { id: 'c', text: '边看手机边走' },
    ],
    answer: 'a',
    explanation: '先看左、再看右、确认两边都没车才通过，全程别玩手机。',
  },
  {
    id: 'high-life-007',
    subject: 'life',
    prompt: '明天课表有数学、英语、体育、美术，整理书包最该先确认的是？',
    choices: [
      { id: 'a', text: '把所有课本都塞进去' },
      { id: 'b', text: '对着课表只装明天要用的' },
      { id: 'c', text: '看心情随便装' },
    ],
    answer: 'b',
    explanation: '照着课表装，既不漏带也不会背一书包用不上的书。',
  },
  {
    id: 'high-life-008',
    subject: 'life',
    prompt: '书桌上文具到处乱放，最有效的收纳办法是？',
    choices: [
      { id: 'a', text: '全堆进一个抽屉' },
      { id: 'b', text: '按类别分格子放，常用的放手边' },
      { id: 'c', text: '都摆在桌面上方便拿' },
    ],
    answer: 'b',
    explanation: '同类归同类、高频放近处，找东西才快，桌面也清爽。',
  },
  {
    id: 'high-life-009',
    subject: 'life',
    prompt: '换季了，夏天的衣服暂时不穿，怎么收最省地方又好找？',
    choices: [
      { id: 'a', text: '叠好放进收纳箱并贴上标签' },
      { id: 'b', text: '随手塞进衣柜最里面' },
      { id: 'c', text: '堆在床底下' },
    ],
    answer: 'a',
    explanation: '分类装箱贴标签，下次换季一眼就能找到，也不占衣柜常用空间。',
  },
  {
    id: 'high-life-010',
    subject: 'life',
    prompt: '一个人在家时门铃响了，对方说是查水表的，你该怎么办？',
    choices: [
      { id: 'a', text: '直接开门让他进来' },
      { id: 'b', text: '隔着门说大人不在，先给爸妈打电话' },
      { id: 'c', text: '假装没人但去开门看看' },
    ],
    answer: 'b',
    explanation: '陌生人上门不要开门，先联系家长核实，安全第一。',
  },
  {
    id: 'high-life-011',
    subject: 'life',
    prompt: '厨房锅里的油突然着火了，最不能做的是哪一件？',
    choices: [
      { id: 'a', text: '关掉火源' },
      { id: 'b', text: '用锅盖盖住灭火' },
      { id: 'c', text: '往锅里泼水' },
    ],
    answer: 'c',
    explanation: '油锅着火泼水会让火爆溅、越烧越大，应该盖锅盖隔绝空气并关火。',
  },
  {
    id: 'high-life-012',
    subject: 'life',
    prompt: '插座或电器进水了，你想拔掉它，正确做法是？',
    choices: [
      { id: 'a', text: '湿手直接去拔插头' },
      { id: 'b', text: '先关总闸，手干了再处理' },
      { id: 'c', text: '用金属夹子去夹' },
    ],
    answer: 'b',
    explanation: '水和湿手都导电，先断总电源、保持手干燥再操作，避免触电。',
  },
  {
    id: 'high-life-013',
    subject: 'life',
    prompt: '别人帮了你一个忙，最得体的回应是？',
    choices: [
      { id: 'a', text: '当作没发生' },
      { id: 'b', text: '真诚地说声谢谢' },
      { id: 'c', text: '默默走开' },
    ],
    answer: 'b',
    explanation: '接受帮助后表达感谢，是基本的礼貌，也让人愿意继续帮你。',
  },
  {
    id: 'high-life-014',
    subject: 'life',
    prompt: '到同学家做客，进门时比较有礼貌的做法是？',
    choices: [
      { id: 'a', text: '主动跟对方家长打招呼' },
      { id: 'b', text: '直接冲进房间玩' },
      { id: 'c', text: '把鞋随便踢在门口' },
    ],
    answer: 'a',
    explanation: '到别人家先和长辈问好、把鞋摆整齐，是受欢迎的客人。',
  },
  {
    id: 'high-life-015',
    subject: 'life',
    prompt: '吃饭时想夹离自己很远的那盘菜，比较有礼貌的做法是？',
    choices: [
      { id: 'a', text: '站起来伸长胳膊去够' },
      { id: 'b', text: '请旁边的人帮忙递一下' },
      { id: 'c', text: '把盘子整个端到自己面前' },
    ],
    answer: 'b',
    explanation: '够不到就客气地请人帮忙传，比起身横扫餐桌更得体。',
  },
  {
    id: 'high-life-016',
    subject: 'life',
    prompt: '天气预报说今天 12 到 28 度、午后有雷阵雨，出门怎么穿带最合适？',
    choices: [
      { id: 'a', text: '穿短袖、带一件薄外套和伞' },
      { id: 'b', text: '只穿短袖什么都不带' },
      { id: 'c', text: '穿厚棉袄' },
    ],
    answer: 'a',
    explanation: '早晚 12 度凉、午间 28 度热，温差大要带薄外套，午后有雨得带伞。',
  },
  {
    id: 'high-life-017',
    subject: 'life',
    prompt: '出门看到天阴沉沉、风也变大了，比较聪明的判断是？',
    choices: [
      { id: 'a', text: '可能要下雨，带把伞' },
      { id: 'b', text: '肯定是大晴天' },
      { id: 'c', text: '和天气没关系' },
    ],
    answer: 'a',
    explanation: '乌云压顶加起风往往是降雨的前兆，带伞有备无患。',
  },
  {
    id: 'high-life-018',
    subject: 'life',
    prompt: '冬天从很热的室内走到很冷的室外，对身体最友好的做法是？',
    choices: [
      { id: 'a', text: '出门前先把外套穿好再走出去' },
      { id: 'b', text: '光着膀子冲出去凉快' },
      { id: 'c', text: '出去后觉得冷再回来加衣' },
    ],
    answer: 'a',
    explanation: '温差大时提前穿好外套，能避免忽冷忽热着凉感冒。',
  },
  {
    id: 'high-life-019',
    subject: 'life',
    prompt: '喝完的塑料矿泉水瓶，应该扔进哪类垃圾桶？',
    choices: [
      { id: 'a', text: '可回收物' },
      { id: 'b', text: '厨余垃圾' },
      { id: 'c', text: '有害垃圾' },
    ],
    answer: 'a',
    explanation: '塑料瓶干净可再利用，属于可回收物，最好先倒空压扁。',
  },
  {
    id: 'high-life-020',
    subject: 'life',
    prompt: '用完的废旧电池和过期药品，应该投到哪一类？',
    choices: [
      { id: 'a', text: '其他垃圾' },
      { id: 'b', text: '有害垃圾' },
      { id: 'c', text: '可回收物' },
    ],
    answer: 'b',
    explanation: '电池、药品含有害物质，要单独投到有害垃圾，不能随便丢。',
  },
  {
    id: 'high-life-021',
    subject: 'life',
    prompt: '吃剩的苹果核和菜叶子，属于哪一类垃圾？',
    choices: [
      { id: 'a', text: '厨余（湿）垃圾' },
      { id: 'b', text: '可回收物' },
      { id: 'c', text: '有害垃圾' },
    ],
    answer: 'a',
    explanation: '果皮、菜叶、剩饭这类容易腐烂的食物残渣属于厨余垃圾。',
  },
  {
    id: 'high-life-022',
    subject: 'life',
    prompt: '一杯没喝完的奶茶要扔掉，最规范的丢弃步骤是？',
    choices: [
      { id: 'a', text: '连杯带奶茶整杯扔进可回收' },
      { id: 'b', text: '倒掉液体、料归厨余，杯子和吸管再分别处理' },
      { id: 'c', text: '随手扔进任意一个桶' },
    ],
    answer: 'b',
    explanation: '先倒掉剩余液体，珍珠等料属厨余，塑料杯和吸管按规定分类，这才是正确的拆分丢弃。',
  },
]
