import type { BattleQuestion } from '../core'

// 高年级数学（六年级，约11-13岁，给闫一依）：分数小数、周长面积、简单应用题、倍数。
// 稍有深度、更机灵，口语化、适龄、不重复，给真实小孩玩的。
export const items: BattleQuestion[] = [
  {
    id: 'high-math-001',
    subject: 'math',
    prompt: '1/2 和 0.5，谁更大？',
    choices: [
      { id: 'a', text: '1/2 更大' },
      { id: 'b', text: '0.5 更大' },
      { id: 'c', text: '一样大' },
    ],
    answer: 'c',
    explanation: '1/2 写成小数就是 0.5，它俩其实是同一个数。',
  },
  {
    id: 'high-math-002',
    subject: 'math',
    prompt: '一个正方形边长 5 厘米，它的周长是多少？',
    choices: [
      { id: 'a', text: '20 厘米' },
      { id: 'b', text: '25 厘米' },
      { id: 'c', text: '10 厘米' },
    ],
    answer: 'a',
    explanation: '正方形四条边一样长，周长 = 5 × 4 = 20 厘米。',
  },
  {
    id: 'high-math-003',
    subject: 'math',
    prompt: '同样这个边长 5 厘米的正方形，面积又是多少？',
    choices: [
      { id: 'a', text: '20 平方厘米' },
      { id: 'b', text: '25 平方厘米' },
      { id: 'c', text: '10 平方厘米' },
    ],
    answer: 'b',
    explanation: '面积 = 边长 × 边长 = 5 × 5 = 25 平方厘米。别和周长搞混啦。',
  },
  {
    id: 'high-math-004',
    subject: 'math',
    prompt: '0.25 化成分数，最简是几分之几？',
    choices: [
      { id: 'a', text: '1/4' },
      { id: 'b', text: '1/2' },
      { id: 'c', text: '2/5' },
    ],
    answer: 'a',
    explanation: '0.25 = 25/100，约分后就是 1/4。',
  },
  {
    id: 'high-math-005',
    subject: 'math',
    prompt: '24 是 6 的几倍？',
    choices: [
      { id: 'a', text: '3 倍' },
      { id: 'b', text: '4 倍' },
      { id: 'c', text: '5 倍' },
    ],
    answer: 'b',
    explanation: '24 ÷ 6 = 4，所以是 4 倍。',
  },
  {
    id: 'high-math-006',
    subject: 'math',
    prompt: '一本书 80 页，你看了 3/4，还剩多少页没看？',
    choices: [
      { id: 'a', text: '20 页' },
      { id: 'b', text: '60 页' },
      { id: 'c', text: '40 页' },
    ],
    answer: 'a',
    explanation: '看了 3/4 就还剩 1/4，80 × 1/4 = 20 页。',
  },
  {
    id: 'high-math-007',
    subject: 'math',
    prompt: '一个长方形长 8 米、宽 3 米，面积是多少？',
    choices: [
      { id: 'a', text: '11 平方米' },
      { id: 'b', text: '22 平方米' },
      { id: 'c', text: '24 平方米' },
    ],
    answer: 'c',
    explanation: '长方形面积 = 长 × 宽 = 8 × 3 = 24 平方米。',
  },
  {
    id: 'high-math-008',
    subject: 'math',
    prompt: '这个长 8 米、宽 3 米的长方形，周长是多少？',
    choices: [
      { id: 'a', text: '22 米' },
      { id: 'b', text: '24 米' },
      { id: 'c', text: '11 米' },
    ],
    answer: 'a',
    explanation: '周长 = (长 + 宽) × 2 = (8 + 3) × 2 = 22 米。',
  },
  {
    id: 'high-math-009',
    subject: 'math',
    prompt: '1/3 + 1/3 等于多少？',
    choices: [
      { id: 'a', text: '1/6' },
      { id: 'b', text: '2/3' },
      { id: 'c', text: '2/6' },
    ],
    answer: 'b',
    explanation: '分母相同，分子相加：1 + 1 = 2，结果是 2/3。',
  },
  {
    id: 'high-math-010',
    subject: 'math',
    prompt: '3.6 + 1.5 等于多少？',
    choices: [
      { id: 'a', text: '5.1' },
      { id: 'b', text: '4.11' },
      { id: 'c', text: '5.0' },
    ],
    answer: 'a',
    explanation: '小数对齐相加：3.6 + 1.5 = 5.1。',
  },
  {
    id: 'high-math-011',
    subject: 'math',
    prompt: '一支笔 2.5 元，买 4 支要多少钱？',
    choices: [
      { id: 'a', text: '8 元' },
      { id: 'b', text: '10 元' },
      { id: 'c', text: '9 元' },
    ],
    answer: 'b',
    explanation: '2.5 × 4 = 10 元。',
  },
  {
    id: 'high-math-012',
    subject: 'math',
    prompt: '下面哪个数是 7 的倍数？',
    choices: [
      { id: 'a', text: '27' },
      { id: 'b', text: '42' },
      { id: 'c', text: '50' },
    ],
    answer: 'b',
    explanation: '42 = 7 × 6，所以是 7 的倍数。',
  },
  {
    id: 'high-math-013',
    subject: 'math',
    prompt: '2/5 化成小数是多少？',
    choices: [
      { id: 'a', text: '0.4' },
      { id: 'b', text: '0.25' },
      { id: 'c', text: '0.5' },
    ],
    answer: 'a',
    explanation: '2 ÷ 5 = 0.4。',
  },
  {
    id: 'high-math-014',
    subject: 'math',
    prompt: '小明跑步 5 分钟跑了 1000 米，他平均每分钟跑多少米？',
    choices: [
      { id: 'a', text: '100 米' },
      { id: 'b', text: '200 米' },
      { id: 'c', text: '500 米' },
    ],
    answer: 'b',
    explanation: '1000 ÷ 5 = 200 米，每分钟跑 200 米。',
  },
  {
    id: 'high-math-015',
    subject: 'math',
    prompt: '一个数的 3 倍是 27，这个数是多少？',
    choices: [
      { id: 'a', text: '9' },
      { id: 'b', text: '24' },
      { id: 'c', text: '81' },
    ],
    answer: 'a',
    explanation: '倒过来算：27 ÷ 3 = 9。',
  },
  {
    id: 'high-math-016',
    subject: 'math',
    prompt: '比较 3/4 和 2/3，谁更大？',
    choices: [
      { id: 'a', text: '3/4 更大' },
      { id: 'b', text: '2/3 更大' },
      { id: 'c', text: '一样大' },
    ],
    answer: 'a',
    explanation: '通分：3/4 = 9/12，2/3 = 8/12，所以 3/4 更大。',
  },
  {
    id: 'high-math-017',
    subject: 'math',
    prompt: '一件衣服原价 100 元，打八折后卖多少钱？',
    choices: [
      { id: 'a', text: '20 元' },
      { id: 'b', text: '80 元' },
      { id: 'c', text: '88 元' },
    ],
    answer: 'b',
    explanation: '八折就是按原价的 80% 卖，100 × 0.8 = 80 元。',
  },
  {
    id: 'high-math-018',
    subject: 'math',
    prompt: '1 减去 0.3 等于多少？',
    choices: [
      { id: 'a', text: '0.7' },
      { id: 'b', text: '0.97' },
      { id: 'c', text: '0.3' },
    ],
    answer: 'a',
    explanation: '把 1 看成 1.0，1.0 - 0.3 = 0.7。',
  },
  {
    id: 'high-math-019',
    subject: 'math',
    prompt: '正方形花坛面积是 36 平方米，它的边长是多少？',
    choices: [
      { id: 'a', text: '6 米' },
      { id: 'b', text: '9 米' },
      { id: 'c', text: '18 米' },
    ],
    answer: 'a',
    explanation: '哪个数乘自己等于 36？6 × 6 = 36，所以边长 6 米。',
  },
  {
    id: 'high-math-020',
    subject: 'math',
    prompt: '一堆糖平分给 4 个人，每人 6 颗，原来一共有多少颗？',
    choices: [
      { id: 'a', text: '10 颗' },
      { id: 'b', text: '24 颗' },
      { id: 'c', text: '2 颗' },
    ],
    answer: 'b',
    explanation: '倒着想：每人 6 颗 × 4 人 = 24 颗。',
  },
  {
    id: 'high-math-021',
    subject: 'math',
    prompt: '把 3/6 约成最简分数是多少？',
    choices: [
      { id: 'a', text: '1/2' },
      { id: 'b', text: '1/3' },
      { id: 'c', text: '3/6' },
    ],
    answer: 'a',
    explanation: '分子分母同时除以 3，得到 1/2。',
  },
  {
    id: 'high-math-022',
    subject: 'math',
    prompt: '妈妈 36 岁，是闫一依年龄的 3 倍，闫一依几岁？',
    choices: [
      { id: 'a', text: '9 岁' },
      { id: 'b', text: '12 岁' },
      { id: 'c', text: '33 岁' },
    ],
    answer: 'b',
    explanation: '36 ÷ 3 = 12，闫一依 12 岁。',
  },
]
