import type { BattleQuestion } from '../core'

// 低年级数学（约6-8岁，一二年级）：20以内加减、比大小、数数、看图数量。
// 口语化、适龄、可看图式，给真实小孩玩的。
export const items: BattleQuestion[] = [
  {
    id: 'low-math-001',
    subject: 'math',
    prompt: '一只手有几根手指头呀？',
    choices: [
      { id: 'a', text: '4根' },
      { id: 'b', text: '5根' },
      { id: 'c', text: '6根' },
    ],
    answer: 'b',
    explanation: '张开一只手数一数：1、2、3、4、5，正好5根。',
  },
  {
    id: 'low-math-002',
    subject: 'math',
    prompt: '🍎🍎🍎 桌上有几个苹果？',
    choices: [
      { id: 'a', text: '2个' },
      { id: 'b', text: '3个' },
      { id: 'c', text: '4个' },
    ],
    answer: 'b',
    explanation: '一个一个数：1个、2个、3个，是3个苹果。',
  },
  {
    id: 'low-math-003',
    subject: 'math',
    prompt: '2 加 3 等于几？',
    choices: [
      { id: 'a', text: '4' },
      { id: 'b', text: '5' },
      { id: 'c', text: '6' },
    ],
    answer: 'b',
    explanation: '2个再添上3个，一起就是5个。',
  },
  {
    id: 'low-math-004',
    subject: 'math',
    prompt: '你有 5 颗糖，吃掉 2 颗，还剩几颗？',
    choices: [
      { id: 'a', text: '2颗' },
      { id: 'b', text: '3颗' },
      { id: 'c', text: '4颗' },
    ],
    answer: 'b',
    explanation: '5颗去掉2颗，还剩下3颗。',
  },
  {
    id: 'low-math-005',
    subject: 'math',
    prompt: '哪个数更大：7 还是 4？',
    choices: [
      { id: 'a', text: '7大' },
      { id: 'b', text: '4大' },
      { id: 'c', text: '一样大' },
    ],
    answer: 'a',
    explanation: '7比4多，所以7更大。',
  },
  {
    id: 'low-math-006',
    subject: 'math',
    prompt: '⭐⭐⭐⭐ 天上有几颗小星星？',
    choices: [
      { id: 'a', text: '3颗' },
      { id: 'b', text: '4颗' },
      { id: 'c', text: '5颗' },
    ],
    answer: 'b',
    explanation: '一颗一颗数：1、2、3、4，是4颗星星。',
  },
  {
    id: 'low-math-007',
    subject: 'math',
    prompt: '6 加 6 等于几？',
    choices: [
      { id: 'a', text: '11' },
      { id: 'b', text: '12' },
      { id: 'c', text: '13' },
    ],
    answer: 'b',
    explanation: '6再加6，就是12。',
  },
  {
    id: 'low-math-008',
    subject: 'math',
    prompt: '10 减 4 等于几？',
    choices: [
      { id: 'a', text: '5' },
      { id: 'b', text: '6' },
      { id: 'c', text: '7' },
    ],
    answer: 'b',
    explanation: '10个拿走4个，还剩6个。',
  },
  {
    id: 'low-math-009',
    subject: 'math',
    prompt: '小猫🐱🐱有2只，小狗🐶有1只，一共几只小动物？',
    choices: [
      { id: 'a', text: '2只' },
      { id: 'b', text: '3只' },
      { id: 'c', text: '4只' },
    ],
    answer: 'b',
    explanation: '2只猫加上1只狗，一共3只。',
  },
  {
    id: 'low-math-010',
    subject: 'math',
    prompt: '数一数：1、2、3、__，横线上应该填几？',
    choices: [
      { id: 'a', text: '4' },
      { id: 'b', text: '5' },
      { id: 'c', text: '6' },
    ],
    answer: 'a',
    explanation: '按顺序数下去，3的后面就是4。',
  },
  {
    id: 'low-math-011',
    subject: 'math',
    prompt: '哪个数最小：8、3、5？',
    choices: [
      { id: 'a', text: '8' },
      { id: 'b', text: '3' },
      { id: 'c', text: '5' },
    ],
    answer: 'b',
    explanation: '3比5小，5比8小，所以3最小。',
  },
  {
    id: 'low-math-012',
    subject: 'math',
    prompt: '9 加 1 等于几？',
    choices: [
      { id: 'a', text: '9' },
      { id: 'b', text: '10' },
      { id: 'c', text: '11' },
    ],
    answer: 'b',
    explanation: '9再添上1，正好凑成10。',
  },
  {
    id: 'low-math-013',
    subject: 'math',
    prompt: '🚗🚗🚗🚗🚗 停车场有几辆小汽车？',
    choices: [
      { id: 'a', text: '4辆' },
      { id: 'b', text: '5辆' },
      { id: 'c', text: '6辆' },
    ],
    answer: 'b',
    explanation: '数一数：1、2、3、4、5，是5辆车。',
  },
  {
    id: 'low-math-014',
    subject: 'math',
    prompt: '7 减 3 等于几？',
    choices: [
      { id: 'a', text: '3' },
      { id: 'b', text: '4' },
      { id: 'c', text: '5' },
    ],
    answer: 'b',
    explanation: '7个去掉3个，还剩4个。',
  },
  {
    id: 'low-math-015',
    subject: 'math',
    prompt: '8 加 5 等于几？',
    choices: [
      { id: 'a', text: '12' },
      { id: 'b', text: '13' },
      { id: 'c', text: '14' },
    ],
    answer: 'b',
    explanation: '8先凑到10要借2，5里拿出2，剩下3，10加3就是13。',
  },
  {
    id: 'low-math-016',
    subject: 'math',
    prompt: '一个星期有几天呀？',
    choices: [
      { id: 'a', text: '5天' },
      { id: 'b', text: '6天' },
      { id: 'c', text: '7天' },
    ],
    answer: 'c',
    explanation: '从星期一数到星期日，一共7天。',
  },
  {
    id: 'low-math-017',
    subject: 'math',
    prompt: '🐟🐟🐟🐟🐟🐟 鱼缸里有几条鱼？',
    choices: [
      { id: 'a', text: '5条' },
      { id: 'b', text: '6条' },
      { id: 'c', text: '7条' },
    ],
    answer: 'b',
    explanation: '一条一条数：1到6，是6条鱼。',
  },
  {
    id: 'low-math-018',
    subject: 'math',
    prompt: '12 比 9 怎么样？',
    choices: [
      { id: 'a', text: '12比9大' },
      { id: 'b', text: '12比9小' },
      { id: 'c', text: '一样多' },
    ],
    answer: 'a',
    explanation: '12比10还多，9比10少，所以12大。',
  },
  {
    id: 'low-math-019',
    subject: 'math',
    prompt: '盘子里有4块饼干，妈妈又放了4块，现在有几块？',
    choices: [
      { id: 'a', text: '7块' },
      { id: 'b', text: '8块' },
      { id: 'c', text: '9块' },
    ],
    answer: 'b',
    explanation: '原来4块，再加4块，一共8块。',
  },
  {
    id: 'low-math-020',
    subject: 'math',
    prompt: '从大往小数：5、4、3、__，横线上填几？',
    choices: [
      { id: 'a', text: '1' },
      { id: 'b', text: '2' },
      { id: 'c', text: '6' },
    ],
    answer: 'b',
    explanation: '一个比一个少1，3的后面就是2。',
  },
  {
    id: 'low-math-021',
    subject: 'math',
    prompt: '20 减 10 等于几？',
    choices: [
      { id: 'a', text: '5' },
      { id: 'b', text: '10' },
      { id: 'c', text: '15' },
    ],
    answer: 'b',
    explanation: '20里拿走10，还剩10。',
  },
  {
    id: 'low-math-022',
    subject: 'math',
    prompt: '🎈🎈🎈🎈🎈🎈🎈 手里有几个气球？',
    choices: [
      { id: 'a', text: '6个' },
      { id: 'b', text: '7个' },
      { id: 'c', text: '8个' },
    ],
    answer: 'b',
    explanation: '一个一个数：1到7，是7个气球。',
  },
]
