import type { BattleQuestion } from '../core'

// 高年级科学（六年级，约11-13岁，给闫一依）：自然现象、简单物理化学常识、人体、地球宇宙。
// 稍有深度、更机灵，口语化、适龄、不重复，给真实小孩玩的。
export const items: BattleQuestion[] = [
  {
    id: 'high-science-001',
    subject: 'science',
    prompt: '天上为什么会打雷？',
    choices: [
      { id: 'a', text: '云里有人在敲鼓' },
      { id: 'b', text: '云里的电放出来，把空气一下子撑开' },
      { id: 'c', text: '太阳掉到云里了' },
    ],
    answer: 'b',
    explanation: '闪电放电瞬间把周围空气加热膨胀，发出的爆响就是雷声。',
  },
  {
    id: 'high-science-002',
    subject: 'science',
    prompt: '为什么先看到闪电、过一会儿才听到雷声？',
    choices: [
      { id: 'a', text: '光比声音跑得快得多' },
      { id: 'b', text: '雷声要先睡个觉' },
      { id: 'c', text: '声音是从地下传上来的' },
    ],
    answer: 'a',
    explanation: '光速约每秒30万公里，声速才约340米/秒，所以光先到。',
  },
  {
    id: 'high-science-003',
    subject: 'science',
    prompt: '彩虹一般是在什么情况下出现的？',
    choices: [
      { id: 'a', text: '空气里有小水珠，太阳把光分开了' },
      { id: 'b', text: '有人在天上涂颜料' },
      { id: 'c', text: '只有晚上才会有' },
    ],
    answer: 'a',
    explanation: '阳光被空气中的小水滴折射、反射，分解成七种颜色就成了彩虹。',
  },
  {
    id: 'high-science-004',
    subject: 'science',
    prompt: '水在标准情况下大约多少摄氏度会沸腾？',
    choices: [
      { id: 'a', text: '50度' },
      { id: 'b', text: '100度' },
      { id: 'c', text: '200度' },
    ],
    answer: 'b',
    explanation: '在海平面标准气压下，水大约100摄氏度沸腾。',
  },
  {
    id: 'high-science-005',
    subject: 'science',
    prompt: '冬天玻璃内侧出现的小水珠，是怎么来的？',
    choices: [
      { id: 'a', text: '从玻璃缝里渗进来的' },
      { id: 'b', text: '屋里热空气碰到冷玻璃，水汽变成了水' },
      { id: 'c', text: '玻璃自己出汗了' },
    ],
    answer: 'b',
    explanation: '这叫凝结：暖湿空气遇冷，水蒸气变回液态水珠。',
  },
  {
    id: 'high-science-006',
    subject: 'science',
    prompt: '同样重的铁块和棉花，哪个更重？',
    choices: [
      { id: 'a', text: '铁块更重' },
      { id: 'b', text: '棉花更重' },
      { id: 'c', text: '一样重' },
    ],
    answer: 'c',
    explanation: '题目说"同样重"，那当然一样重，棉花只是占的地方更大。',
  },
  {
    id: 'high-science-007',
    subject: 'science',
    prompt: '人体里负责把氧气送到全身的，主要是什么？',
    choices: [
      { id: 'a', text: '红细胞（血液里的红色细胞）' },
      { id: 'b', text: '骨头' },
      { id: 'c', text: '指甲' },
    ],
    answer: 'a',
    explanation: '红细胞里的血红蛋白能抓住氧气，随血液送到身体各处。',
  },
  {
    id: 'high-science-008',
    subject: 'science',
    prompt: '我们呼吸时吸进去的、最有用的气体是哪种？',
    choices: [
      { id: 'a', text: '二氧化碳' },
      { id: 'b', text: '氧气' },
      { id: 'c', text: '氢气' },
    ],
    answer: 'b',
    explanation: '身体靠氧气把食物里的能量"烧"出来，再把二氧化碳呼出去。',
  },
  {
    id: 'high-science-009',
    subject: 'science',
    prompt: '一天有白天和黑夜，主要是因为什么？',
    choices: [
      { id: 'a', text: '太阳自己开关灯' },
      { id: 'b', text: '地球在自转（自己转圈）' },
      { id: 'c', text: '月亮挡住了太阳' },
    ],
    answer: 'b',
    explanation: '地球大约24小时自转一圈，朝着太阳的那面是白天，背面是黑夜。',
  },
  {
    id: 'high-science-010',
    subject: 'science',
    prompt: '一年有四季，主要跟什么有关？',
    choices: [
      { id: 'a', text: '地球离太阳忽远忽近，而且地轴是斜的' },
      { id: 'b', text: '太阳每年换一次灯泡' },
      { id: 'c', text: '云的颜色会变' },
    ],
    answer: 'a',
    explanation: '地轴倾斜，地球绕太阳公转时各地受到的阳光角度变化，就有了四季。',
  },
  {
    id: 'high-science-011',
    subject: 'science',
    prompt: '月亮自己会发光吗？',
    choices: [
      { id: 'a', text: '会，它是个大灯泡' },
      { id: 'b', text: '不会，它是反射太阳的光' },
      { id: 'c', text: '只有满月时会发光' },
    ],
    answer: 'b',
    explanation: '月亮不发光，我们看到的月光其实是它反射的太阳光。',
  },
  {
    id: 'high-science-012',
    subject: 'science',
    prompt: '把盐放进水里搅一搅就看不见了，这叫什么？',
    choices: [
      { id: 'a', text: '盐消失了' },
      { id: 'b', text: '盐溶解了，变成很小的粒子混在水里' },
      { id: 'c', text: '盐飞走了' },
    ],
    answer: 'b',
    explanation: '盐没有消失，只是溶解后分散得很均匀，把水蒸干还能找回盐。',
  },
  {
    id: 'high-science-013',
    subject: 'science',
    prompt: '铁放在潮湿的地方久了会生锈，这其实是什么过程？',
    choices: [
      { id: 'a', text: '铁和空气里的氧气、水发生了化学变化' },
      { id: 'b', text: '铁被晒黑了' },
      { id: 'c', text: '铁长出了苔藓' },
    ],
    answer: 'a',
    explanation: '生锈是铁慢慢和氧气、水反应生成铁锈，是一种化学变化。',
  },
  {
    id: 'high-science-014',
    subject: 'science',
    prompt: '声音能在下面哪种环境里传播？',
    choices: [
      { id: 'a', text: '太空真空里' },
      { id: 'b', text: '空气、水和固体里' },
      { id: 'c', text: '哪儿都传不了' },
    ],
    answer: 'b',
    explanation: '声音要靠物质振动传播，真空里没有介质，所以太空很安静。',
  },
  {
    id: 'high-science-015',
    subject: 'science',
    prompt: '植物白天靠阳光自己造"饭吃"，这个过程叫什么？',
    choices: [
      { id: 'a', text: '光合作用' },
      { id: 'b', text: '消化作用' },
      { id: 'c', text: '发电作用' },
    ],
    answer: 'a',
    explanation: '光合作用：植物用阳光、水和二氧化碳造出养分，同时放出氧气。',
  },
  {
    id: 'high-science-016',
    subject: 'science',
    prompt: '海里的水那么多，为什么不会越涨越多漫出来？',
    choices: [
      { id: 'a', text: '有人偷偷抽走了' },
      { id: 'b', text: '海水蒸发变成云，又下雨回到陆地和海里，循环着' },
      { id: 'c', text: '鱼把水喝掉了' },
    ],
    answer: 'b',
    explanation: '这就是水循环：蒸发、成云、降雨、汇流，水一直在地球上转圈。',
  },
  {
    id: 'high-science-017',
    subject: 'science',
    prompt: '磁铁最容易吸住下面哪个东西？',
    choices: [
      { id: 'a', text: '塑料尺' },
      { id: 'b', text: '回形针（铁的）' },
      { id: 'c', text: '玻璃杯' },
    ],
    answer: 'b',
    explanation: '磁铁能吸引铁、镍等金属，塑料和玻璃都不会被吸。',
  },
  {
    id: 'high-science-018',
    subject: 'science',
    prompt: '人的心脏一直在干什么活儿？',
    choices: [
      { id: 'a', text: '帮我们思考问题' },
      { id: 'b', text: '像泵一样把血液送到全身' },
      { id: 'c', text: '负责消化食物' },
    ],
    answer: 'b',
    explanation: '心脏是个"泵"，不停收缩把血液压送到全身再收回来。',
  },
  {
    id: 'high-science-019',
    subject: 'science',
    prompt: '为什么松开手，苹果会往下掉而不是往上飞？',
    choices: [
      { id: 'a', text: '苹果怕高' },
      { id: 'b', text: '因为地球有引力，把东西往下拉' },
      { id: 'c', text: '因为空气在往下吹' },
    ],
    answer: 'b',
    explanation: '地球的重力（引力）把物体往地心方向拉，所以东西会往下落。',
  },
  {
    id: 'high-science-020',
    subject: 'science',
    prompt: '把同一根筷子斜着插进水杯，看起来像断了，这是为什么？',
    choices: [
      { id: 'a', text: '筷子真的断了' },
      { id: 'b', text: '光从水里出来时拐了个弯（折射）' },
      { id: 'c', text: '水把筷子咬断了' },
    ],
    answer: 'b',
    explanation: '光从水进入空气时会折射改变方向，看起来筷子就像错位了。',
  },
  {
    id: 'high-science-021',
    subject: 'science',
    prompt: '在我们太阳系里，离太阳最近的行星是哪个？',
    choices: [
      { id: 'a', text: '地球' },
      { id: 'b', text: '木星' },
      { id: 'c', text: '水星' },
    ],
    answer: 'c',
    explanation: '从太阳往外数，第一颗行星是水星，离太阳最近。',
  },
  {
    id: 'high-science-022',
    subject: 'science',
    prompt: '夏天打开冰箱门，门口冒"白气"，这白气其实是什么？',
    choices: [
      { id: 'a', text: '是冰箱在放电' },
      { id: 'b', text: '空气里的水汽遇冷凝成的小水珠' },
      { id: 'c', text: '是烟' },
    ],
    answer: 'b',
    explanation: '冰箱里冒出的冷气让周围水蒸气凝结成小水珠，看起来就像白雾。',
  },
]
