import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'low-science-001',
    subject: 'science',
    prompt: '小狗高兴的时候，会怎么摇？',
    choices: [
      { id: 'a', text: '摇尾巴' },
      { id: 'b', text: '摇耳朵' },
      { id: 'c', text: '摇鼻子' },
    ],
    answer: 'a',
    explanation: '小狗开心或者亲近你的时候，会摇摇小尾巴。',
  },
  {
    id: 'low-science-002',
    subject: 'science',
    prompt: '小兔子最爱吃下面哪个呀？',
    choices: [
      { id: 'a', text: '骨头' },
      { id: 'b', text: '胡萝卜和青菜' },
      { id: 'c', text: '小鱼' },
    ],
    answer: 'b',
    explanation: '小兔子爱吃胡萝卜、青草和青菜这些植物。',
  },
  {
    id: 'low-science-003',
    subject: 'science',
    prompt: '小鸟是用什么飞到天上的？',
    choices: [
      { id: 'a', text: '用腿跳' },
      { id: 'b', text: '用翅膀' },
      { id: 'c', text: '用尾巴' },
    ],
    answer: 'b',
    explanation: '小鸟扇动翅膀，就能飞起来啦。',
  },
  {
    id: 'low-science-004',
    subject: 'science',
    prompt: '下雨之前，天上的云一般是什么样子？',
    choices: [
      { id: 'a', text: '灰灰黑黑的' },
      { id: 'b', text: '亮亮白白的' },
      { id: 'c', text: '没有云' },
    ],
    answer: 'a',
    explanation: '快下雨的时候，云会变得灰灰黑黑、厚厚的。',
  },
  {
    id: 'low-science-005',
    subject: 'science',
    prompt: '冬天很冷的时候，水会变成什么？',
    choices: [
      { id: 'a', text: '冰' },
      { id: 'b', text: '糖' },
      { id: 'c', text: '油' },
    ],
    answer: 'a',
    explanation: '天太冷的时候，水会结成硬硬的冰。',
  },
  {
    id: 'low-science-006',
    subject: 'science',
    prompt: '我们用身体的哪个部分来闻香味？',
    choices: [
      { id: 'a', text: '耳朵' },
      { id: 'b', text: '鼻子' },
      { id: 'c', text: '手' },
    ],
    answer: 'b',
    explanation: '我们用鼻子来闻花香、闻饭香。',
  },
  {
    id: 'low-science-007',
    subject: 'science',
    prompt: '我们用哪里来听声音？',
    choices: [
      { id: 'a', text: '眼睛' },
      { id: 'b', text: '嘴巴' },
      { id: 'c', text: '耳朵' },
    ],
    answer: 'c',
    explanation: '耳朵是用来听声音的，听爸爸妈妈说话、听音乐。',
  },
  {
    id: 'low-science-008',
    subject: 'science',
    prompt: '一只手有几根手指头？',
    choices: [
      { id: 'a', text: '三根' },
      { id: 'b', text: '五根' },
      { id: 'c', text: '十根' },
    ],
    answer: 'b',
    explanation: '一只手有五根手指，两只手加起来是十根。',
  },
  {
    id: 'low-science-009',
    subject: 'science',
    prompt: '小树苗想长大，最需要什么？',
    choices: [
      { id: 'a', text: '糖果' },
      { id: 'b', text: '阳光和水' },
      { id: 'c', text: '玩具' },
    ],
    answer: 'b',
    explanation: '植物要晒太阳、要喝水，才能慢慢长大。',
  },
  {
    id: 'low-science-010',
    subject: 'science',
    prompt: '花一般是从哪里长出来的？',
    choices: [
      { id: 'a', text: '从天上掉下来' },
      { id: 'b', text: '从植物上开出来' },
      { id: 'c', text: '从水里冒出来' },
    ],
    answer: 'b',
    explanation: '花是植物开出来的，先有花骨朵，再慢慢开放。',
  },
  {
    id: 'low-science-011',
    subject: 'science',
    prompt: '小鱼住在哪里呀？',
    choices: [
      { id: 'a', text: '水里' },
      { id: 'b', text: '树上' },
      { id: 'c', text: '天上' },
    ],
    answer: 'a',
    explanation: '小鱼用鳃呼吸，住在水里，离开水会不舒服。',
  },
  {
    id: 'low-science-012',
    subject: 'science',
    prompt: '太阳出来的时候，天气一般是怎样的？',
    choices: [
      { id: 'a', text: '晴天，亮亮的' },
      { id: 'b', text: '黑漆漆的' },
      { id: 'c', text: '下大雪' },
    ],
    answer: 'a',
    explanation: '太阳高高挂着、没有乌云，就是晴天。',
  },
  {
    id: 'low-science-013',
    subject: 'science',
    prompt: '下雪天，外面会变成什么颜色？',
    choices: [
      { id: 'a', text: '白白的' },
      { id: 'b', text: '红红的' },
      { id: 'c', text: '绿绿的' },
    ],
    answer: 'a',
    explanation: '雪是白色的，下完雪，地上、树上都变白啦。',
  },
  {
    id: 'low-science-014',
    subject: 'science',
    prompt: '小猫喜欢用什么声音叫？',
    choices: [
      { id: 'a', text: '汪汪' },
      { id: 'b', text: '喵喵' },
      { id: 'c', text: '咕咕' },
    ],
    answer: 'b',
    explanation: '小猫叫起来是“喵喵”，小狗才是“汪汪”。',
  },
  {
    id: 'low-science-015',
    subject: 'science',
    prompt: '我们用身体的哪里来走路、跑步？',
    choices: [
      { id: 'a', text: '腿和脚' },
      { id: 'b', text: '头' },
      { id: 'c', text: '肚子' },
    ],
    answer: 'a',
    explanation: '我们用两条腿和脚走路、跑步、跳来跳去。',
  },
  {
    id: 'low-science-016',
    subject: 'science',
    prompt: '小蜜蜂飞到花上，是去做什么？',
    choices: [
      { id: 'a', text: '采花蜜' },
      { id: 'b', text: '睡觉' },
      { id: 'c', text: '洗澡' },
    ],
    answer: 'a',
    explanation: '小蜜蜂在花上采花蜜，回去做成甜甜的蜂蜜。',
  },
  {
    id: 'low-science-017',
    subject: 'science',
    prompt: '刮大风的时候，树叶会怎么样？',
    choices: [
      { id: 'a', text: '一动不动' },
      { id: 'b', text: '摇来摇去、飘起来' },
      { id: 'c', text: '变成红色' },
    ],
    answer: 'b',
    explanation: '风一吹，树枝树叶就会摇晃，叶子也会飘起来。',
  },
  {
    id: 'low-science-018',
    subject: 'science',
    prompt: '牙齿是用来做什么的？',
    choices: [
      { id: 'a', text: '看东西' },
      { id: 'b', text: '咬东西、嚼食物' },
      { id: 'c', text: '听声音' },
    ],
    answer: 'b',
    explanation: '牙齿帮我们咬东西、嚼食物，要好好刷牙保护它。',
  },
  {
    id: 'low-science-019',
    subject: 'science',
    prompt: '大象的鼻子有什么特别的地方？',
    choices: [
      { id: 'a', text: '又长又能卷东西' },
      { id: 'b', text: '会发光' },
      { id: 'c', text: '会唱歌' },
    ],
    answer: 'a',
    explanation: '大象的鼻子又长又灵活，能卷起食物、还能吸水。',
  },
  {
    id: 'low-science-020',
    subject: 'science',
    prompt: '青蛙小时候叫什么？',
    choices: [
      { id: 'a', text: '小蝌蚪' },
      { id: 'b', text: '小蚂蚁' },
      { id: 'c', text: '小蜗牛' },
    ],
    answer: 'a',
    explanation: '青蛙小时候是黑黑的小蝌蚪，长大才变成青蛙。',
  },
  {
    id: 'low-science-021',
    subject: 'science',
    prompt: '我们的眼睛是用来做什么的？',
    choices: [
      { id: 'a', text: '看东西' },
      { id: 'b', text: '吃饭' },
      { id: 'c', text: '走路' },
    ],
    answer: 'a',
    explanation: '眼睛帮我们看东西，看书的时候要注意保护眼睛。',
  },
  {
    id: 'low-science-022',
    subject: 'science',
    prompt: '到了晚上，天上会出现什么？',
    choices: [
      { id: 'a', text: '太阳' },
      { id: 'b', text: '月亮和星星' },
      { id: 'c', text: '彩虹' },
    ],
    answer: 'b',
    explanation: '白天有太阳，到了晚上就能看到月亮和一闪一闪的星星。',
  },
]
