import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'low-social-001',
    subject: 'social',
    prompt: '同桌借了你的橡皮，过了好几天还没还，你想要回来，怎么说最好？',
    choices: [
      { id: 'a', text: '“你怎么老不还，赖皮！”' },
      { id: 'b', text: '“我的橡皮你用完了吗？能还给我啦～”' },
      { id: 'c', text: '什么都不说，偷偷从他书包里拿走' },
    ],
    answer: 'b',
    explanation: '好好提醒一下就行，对方多半是忘了，温柔说话朋友更愿意还。',
  },
  {
    id: 'low-social-002',
    subject: 'social',
    prompt: '排队打饭的时候，有个小朋友想插到你前面，你说哪句最棒？',
    choices: [
      { id: 'a', text: '“后面排队哦，大家都在等呢。”' },
      { id: 'b', text: '使劲把他推开' },
      { id: 'c', text: '“你再插队我就告诉全班！”' },
    ],
    answer: 'a',
    explanation: '提醒排队既守规矩又不吵架，是最聪明的做法。',
  },
  {
    id: 'low-social-003',
    subject: 'social',
    prompt: '分组做游戏，没人选你，你心里有点难过，怎么做最好？',
    choices: [
      { id: 'a', text: '一个人躲在角落生闷气' },
      { id: 'b', text: '走过去笑着问：“我可以加入你们吗？”' },
      { id: 'c', text: '大哭着说“你们都不喜欢我”' },
    ],
    answer: 'b',
    explanation: '主动问一句，大多数小朋友都会欢迎你，勇敢一点就好啦。',
  },
  {
    id: 'low-social-004',
    subject: 'social',
    prompt: '今天轮到你和小明一起值日，可小明跑出去玩了，你该怎么办？',
    choices: [
      { id: 'a', text: '我也不扫了，撒手就走' },
      { id: 'b', text: '去找小明：“一起扫吧，扫完我们就能去玩啦！”' },
      { id: 'c', text: '把垃圾全推到小明的座位下面' },
    ],
    answer: 'b',
    explanation: '叫上小朋友一起干，活儿做得快，还不会闹矛盾。',
  },
  {
    id: 'low-social-005',
    subject: 'social',
    prompt: '你和好朋友因为抢秋千吵架了，现在你想和好，怎么开口最好？',
    choices: [
      { id: 'a', text: '“刚才我也有不对，我们一起玩好不好？”' },
      { id: 'b', text: '等他先来道歉，不然就不理他' },
      { id: 'c', text: '“哼，再也不跟你玩了！”' },
    ],
    answer: 'a',
    explanation: '先伸出手的人最勇敢，一句“我们一起玩”就能把朋友找回来。',
  },
  {
    id: 'low-social-006',
    subject: 'social',
    prompt: '同学不小心碰倒了你的水杯，水洒了一桌子，他连说对不起，你怎么回最好？',
    choices: [
      { id: 'a', text: '“没关系，我们一起擦干净吧。”' },
      { id: 'b', text: '“你赔我！哭哭哭！”' },
      { id: 'c', text: '也去碰倒他的水杯' },
    ],
    answer: 'a',
    explanation: '别人是不小心的，说声没关系再一起收拾，大家都开心。',
  },
  {
    id: 'low-social-007',
    subject: 'social',
    prompt: '你想用同学的彩笔画画，正确的做法是？',
    choices: [
      { id: 'a', text: '不打招呼直接拿来用' },
      { id: 'b', text: '问一句：“可以借我用一下彩笔吗？”' },
      { id: 'c', text: '趁他不在偷偷拿走' },
    ],
    answer: 'b',
    explanation: '借东西先问一声，是对小朋友的尊重，对方也更乐意借给你。',
  },
  {
    id: 'low-social-008',
    subject: 'social',
    prompt: '你借了同学的故事书，不小心折了一页，怎么做最棒？',
    choices: [
      { id: 'a', text: '假装没看见，悄悄还回去' },
      { id: 'b', text: '把书藏起来不还了' },
      { id: 'c', text: '把页角抚平，告诉他：“对不起，我不小心折到了。”' },
    ],
    answer: 'c',
    explanation: '诚实说出来才是好朋友，藏起来反而会让对方更难过。',
  },
  {
    id: 'low-social-009',
    subject: 'social',
    prompt: '上课时新来的同学找不到铅笔，急得快哭了，你会怎么做？',
    choices: [
      { id: 'a', text: '小声说：“别急，我借你一支。”' },
      { id: 'b', text: '笑他：“连铅笔都没有！”' },
      { id: 'c', text: '装作没看见' },
    ],
    answer: 'a',
    explanation: '帮一把新同学，他会记住你的好，你们说不定就成了朋友。',
  },
  {
    id: 'low-social-010',
    subject: 'social',
    prompt: '做手工，组里只有一把剪刀，大家都想先用，怎么办最好？',
    choices: [
      { id: 'a', text: '抢到手里谁也不给' },
      { id: 'b', text: '“我们一个一个轮流用吧。”' },
      { id: 'c', text: '把剪刀藏到自己抽屉里' },
    ],
    answer: 'b',
    explanation: '轮流用最公平，谁都能玩到，组里也不会吵架。',
  },
  {
    id: 'low-social-011',
    subject: 'social',
    prompt: '有同学叫你的外号取笑你，你又生气又难过，最聪明的回应是？',
    choices: [
      { id: 'a', text: '也给他取个更难听的外号' },
      { id: 'b', text: '认真地说：“我不喜欢这个外号，请叫我的名字。”' },
      { id: 'c', text: '动手打他' },
    ],
    answer: 'b',
    explanation: '清清楚楚说出自己的感受，比吵架打架更有力量。',
  },
  {
    id: 'low-social-012',
    subject: 'social',
    prompt: '你和同学都说自己跑得最快，谁也不让谁，怎么解决最好玩？',
    choices: [
      { id: 'a', text: '“那我们比一场，输了也不许哭哦！”' },
      { id: 'b', text: '“你才跑不快，吹牛！”' },
      { id: 'c', text: '气得不理他了' },
    ],
    answer: 'a',
    explanation: '与其吵嘴，不如来一场快乐的比赛，结果一比就知道啦。',
  },
  {
    id: 'low-social-013',
    subject: 'social',
    prompt: '好朋友今天没带午饭的水果，眼巴巴看着你的，你会怎么做？',
    choices: [
      { id: 'a', text: '“我分你一半，我们一起吃！”' },
      { id: 'b', text: '赶紧全部吃光' },
      { id: 'c', text: '“这是我的，不给你！”' },
    ],
    answer: 'a',
    explanation: '分享一半，快乐变成两份，好朋友就是这样越来越亲。',
  },
  {
    id: 'low-social-014',
    subject: 'social',
    prompt: '小组比赛，你们组输了，有人开始怪队友，你说哪句最暖心？',
    choices: [
      { id: 'a', text: '“都怪你，要不是你我们就赢了！”' },
      { id: 'b', text: '“没关系，下次我们一起加油！”' },
      { id: 'c', text: '“这组太差了，我不玩了。”' },
    ],
    answer: 'b',
    explanation: '输了不怪人、一起想下次，这样的队友谁都喜欢。',
  },
  {
    id: 'low-social-015',
    subject: 'social',
    prompt: '你看到两个同学吵架，越吵越凶，你能帮的好办法是？',
    choices: [
      { id: 'a', text: '凑过去喊“打起来打起来”' },
      { id: 'b', text: '走开当没看见' },
      { id: 'c', text: '劝一劝：“别吵啦，有话好好说，要不要找老师帮忙？”' },
    ],
    answer: 'c',
    explanation: '当个小小和事佬，劝几句或请老师帮忙，比起哄要好得多。',
  },
  {
    id: 'low-social-016',
    subject: 'social',
    prompt: '同学送了你一张他亲手画的画，可你不太喜欢，怎么回最有礼貌？',
    choices: [
      { id: 'a', text: '“好难看，我不要。”' },
      { id: 'b', text: '“谢谢你！你画画送给我，我很开心。”' },
      { id: 'c', text: '一把把画揉成团' },
    ],
    answer: 'b',
    explanation: '别人的心意要珍惜，说声谢谢，对方画得更带劲啦。',
  },
  {
    id: 'low-social-017',
    subject: 'social',
    prompt: '你不小心踩到了同学的脚，他“哎哟”叫了一声，你该怎么做？',
    choices: [
      { id: 'a', text: '赶紧说：“对不起，踩疼你了吗？”' },
      { id: 'b', text: '装作不是自己踩的' },
      { id: 'c', text: '“谁让你脚伸那么长！”' },
    ],
    answer: 'a',
    explanation: '一句真诚的对不起，能让小磕碰马上变得没什么大不了。',
  },
  {
    id: 'low-social-018',
    subject: 'social',
    prompt: '排队的时候你前面的小朋友系鞋带蹲下了，后面的人都急着往前挤，你怎么做最好？',
    choices: [
      { id: 'a', text: '推他一把：“快点啦！”' },
      { id: 'b', text: '等他一下：“别急，你系好我们再走。”' },
      { id: 'c', text: '从他身上跨过去' },
    ],
    answer: 'b',
    explanation: '多等一小会儿，给别人一点时间，队伍照样很快就走起来。',
  },
  {
    id: 'low-social-019',
    subject: 'social',
    prompt: '值日时你已经扫完地了，可同学的活儿还没干完，你会怎么做？',
    choices: [
      { id: 'a', text: '“我扫完了，我先走啦，拜拜！”' },
      { id: 'b', text: '“我帮你一起擦黑板吧，快一点！”' },
      { id: 'c', text: '坐在旁边看他干，还催他快点' },
    ],
    answer: 'b',
    explanation: '搭把手帮同学，活儿干得快，你也会被夸是好帮手。',
  },
  {
    id: 'low-social-020',
    subject: 'social',
    prompt: '同学约你下课一起玩，可你今天想自己安静地看书，怎么说最好？',
    choices: [
      { id: 'a', text: '“今天我想看会儿书，明天再一起玩好吗？”' },
      { id: 'b', text: '“别烦我！”' },
      { id: 'c', text: '不说话扭头就走' },
    ],
    answer: 'a',
    explanation: '不想去也能好好说，约下次一起玩，朋友就不会误会你。',
  },
  {
    id: 'low-social-021',
    subject: 'social',
    prompt: '你和同学闹了别扭一整天，放学想和好，怎么做最暖？',
    choices: [
      { id: 'a', text: '走过去说：“我们别生气啦，明天一起上学好不好？”' },
      { id: 'b', text: '继续板着脸谁也不理' },
      { id: 'c', text: '回家跟妈妈说他坏话' },
    ],
    answer: 'a',
    explanation: '别让小别扭过夜，主动说和好，明天又是开开心心的一天。',
  },
  {
    id: 'low-social-022',
    subject: 'social',
    prompt: '同学借了你的尺子，到了放学还在用，你提醒他还，他说“等一下”，你怎么回最棒？',
    choices: [
      { id: 'a', text: '“好，那你用完记得还我哦，我等你。”' },
      { id: 'b', text: '直接抢过来：“给我！”' },
      { id: 'c', text: '“你再不还我就再也不借你了！”' },
    ],
    answer: 'a',
    explanation: '耐心等一会儿、再轻轻提醒，既守住了东西又守住了朋友。',
  },
]
