import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'high-sports-001',
    subject: 'sports',
    prompt: '篮球比赛里，球员站在三分线外投进一球，能得几分？',
    choices: [
      { id: 'a', text: '2分' },
      { id: 'b', text: '3分' },
      { id: 'c', text: '1分' },
    ],
    answer: 'b',
    explanation: '三分线外投中得3分，线内投中是2分，罚球1分。',
  },
  {
    id: 'high-sports-002',
    subject: 'sports',
    prompt: '足球比赛中，球被踢出底线、最后碰到的是防守方球员，应该判什么？',
    choices: [
      { id: 'a', text: '角球' },
      { id: 'b', text: '球门球' },
      { id: 'c', text: '点球' },
    ],
    answer: 'a',
    explanation: '防守方最后碰球出底线，判进攻方角球；进攻方碰出去才是球门球。',
  },
  {
    id: 'high-sports-003',
    subject: 'sports',
    prompt: '排球比赛里，每队最多可以连续触球几次再把球打过网？',
    choices: [
      { id: 'a', text: '2次' },
      { id: 'b', text: '3次' },
      { id: 'c', text: '4次' },
    ],
    answer: 'b',
    explanation: '一般是“一传、二传、扣球”三次内必须过网，超过算违例（拦网那次不计入）。',
  },
  {
    id: 'high-sports-004',
    subject: 'sports',
    prompt: '一个标准田径跑道，最内圈跑一圈是多少米？',
    choices: [
      { id: 'a', text: '200米' },
      { id: 'b', text: '400米' },
      { id: 'c', text: '500米' },
    ],
    answer: 'b',
    explanation: '标准操场内圈一圈400米，所以跑1000米要跑两圈半。',
  },
  {
    id: 'high-sports-005',
    subject: 'sports',
    prompt: '田径短跑比赛起跑时，发令枪响之前就抢跑，叫什么？',
    choices: [
      { id: 'a', text: '犯规（抢跑）' },
      { id: 'b', text: '加速' },
      { id: 'c', text: '热身' },
    ],
    answer: 'a',
    explanation: '枪响前起动叫抢跑，属于犯规，正式比赛抢跑一次就可能被取消资格。',
  },
  {
    id: 'high-sports-006',
    subject: 'sports',
    prompt: '体育课跑步前先慢跑、拉伸，最主要是为了什么？',
    choices: [
      { id: 'a', text: '让身体热起来、减少受伤' },
      { id: 'b', text: '浪费时间' },
      { id: 'c', text: '让人变高' },
    ],
    answer: 'a',
    explanation: '热身能让肌肉和关节活动开，降低拉伤、扭伤的风险。',
  },
  {
    id: 'high-sports-007',
    subject: 'sports',
    prompt: '乒乓球单局比赛，一般要先到多少分、并且领先2分才算赢？',
    choices: [
      { id: 'a', text: '11分' },
      { id: 'b', text: '15分' },
      { id: 'c', text: '21分' },
    ],
    answer: 'a',
    explanation: '现在用11分制，但10平之后要一直打到领先对手2分为止。',
  },
  {
    id: 'high-sports-008',
    subject: 'sports',
    prompt: '羽毛球比赛中，球落在界线“压线”上，算界内还是界外？',
    choices: [
      { id: 'a', text: '界内（好球）' },
      { id: 'b', text: '界外' },
      { id: 'c', text: '重发' },
    ],
    answer: 'a',
    explanation: '球只要碰到界线就算界内，所以压线是好球。',
  },
  {
    id: 'high-sports-009',
    subject: 'sports',
    prompt: '立定跳远测的主要是身体的什么能力？',
    choices: [
      { id: 'a', text: '腿部爆发力' },
      { id: 'b', text: '记忆力' },
      { id: 'c', text: '视力' },
    ],
    answer: 'a',
    explanation: '立定跳远靠腿一下子用力蹬地起跳，主要测下肢爆发力。',
  },
  {
    id: 'high-sports-010',
    subject: 'sports',
    prompt: '体测里的“坐位体前屈”主要测的是什么？',
    choices: [
      { id: 'a', text: '身体的柔韧性' },
      { id: 'b', text: '跑步速度' },
      { id: 'c', text: '肺活量' },
    ],
    answer: 'a',
    explanation: '坐着伸手往前够，看能伸多远，测的是腰背和腿部的柔韧性。',
  },
  {
    id: 'high-sports-011',
    subject: 'sports',
    prompt: '肺活量测试，主要反映的是身体哪个方面的能力？',
    choices: [
      { id: 'a', text: '一口气能呼出多少空气（呼吸能力）' },
      { id: 'b', text: '能跳多高' },
      { id: 'c', text: '握力大小' },
    ],
    answer: 'a',
    explanation: '肺活量就是深吸一口气后尽力呼出的气体总量，反映呼吸系统强弱。',
  },
  {
    id: 'high-sports-012',
    subject: 'sports',
    prompt: '运动中突然腿抽筋了，最该先做的是什么？',
    choices: [
      { id: 'a', text: '停下来，慢慢拉伸抽筋的肌肉' },
      { id: 'b', text: '继续用力跑' },
      { id: 'c', text: '使劲跳几下' },
    ],
    answer: 'a',
    explanation: '抽筋时要停下来轻轻拉伸、按摩那块肌肉，硬撑容易拉伤。',
  },
  {
    id: 'high-sports-013',
    subject: 'sports',
    prompt: '剧烈运动后，下面哪种做法更合适？',
    choices: [
      { id: 'a', text: '马上猛灌冰水、立刻坐下' },
      { id: 'b', text: '先慢走放松、少量多次喝温水' },
      { id: 'c', text: '立刻冲冷水澡' },
    ],
    answer: 'b',
    explanation: '运动后要慢慢平复，小口多次补水，猛灌冰水或立刻坐下都对身体不好。',
  },
  {
    id: 'high-sports-014',
    subject: 'sports',
    prompt: '一场足球比赛上半场一般踢多长时间？',
    choices: [
      { id: 'a', text: '30分钟' },
      { id: 'b', text: '45分钟' },
      { id: 'c', text: '60分钟' },
    ],
    answer: 'b',
    explanation: '足球上下半场各45分钟，中间还有补时，总共约90分钟。',
  },
  {
    id: 'high-sports-015',
    subject: 'sports',
    prompt: '篮球比赛中，进攻方在自己半场最多停留多少秒就必须把球推过中线？',
    choices: [
      { id: 'a', text: '8秒' },
      { id: 'b', text: '3秒' },
      { id: 'c', text: '24秒' },
    ],
    answer: 'a',
    explanation: '这是“8秒规则”，要在8秒内把球带过中场；24秒是整轮进攻的限时。',
  },
  {
    id: 'high-sports-016',
    subject: 'sports',
    prompt: '跳高比赛里，现在运动员最常用的过杆姿势叫什么？',
    choices: [
      { id: 'a', text: '背越式' },
      { id: 'b', text: '蛙跳式' },
      { id: 'c', text: '前滚翻式' },
    ],
    answer: 'a',
    explanation: '背越式是背朝横杆翻过去，是目前最高效、用得最多的跳高姿势。',
  },
  {
    id: 'high-sports-017',
    subject: 'sports',
    prompt: '游泳前最重要的安全准备是什么？',
    choices: [
      { id: 'a', text: '下水前做好热身、不在不熟悉的水域逞强' },
      { id: 'b', text: '吃得很饱再下水' },
      { id: 'c', text: '比谁憋气憋得久' },
    ],
    answer: 'a',
    explanation: '游泳前要热身防抽筋，别去陌生深水区，也别空腹或刚吃饱就下水。',
  },
  {
    id: 'high-sports-018',
    subject: 'sports',
    prompt: '马拉松全程大约是多少公里？',
    choices: [
      { id: 'a', text: '约10公里' },
      { id: 'b', text: '约42公里' },
      { id: 'c', text: '约100公里' },
    ],
    answer: 'b',
    explanation: '马拉松全程约42.195公里，是非常考验耐力的长跑项目。',
  },
  {
    id: 'high-sports-019',
    subject: 'sports',
    prompt: '判断有氧运动够不够，常说要让什么“跟上来”？',
    choices: [
      { id: 'a', text: '心率（心跳加快、微微出汗）' },
      { id: 'b', text: '体重一下变轻' },
      { id: 'c', text: '个子马上长高' },
    ],
    answer: 'a',
    explanation: '有氧运动要让心跳和呼吸加快、身体微微发热出汗，这样才有锻炼效果。',
  },
  {
    id: 'high-sports-020',
    subject: 'sports',
    prompt: '足球场上，守门员可以用手接球，主要是在什么范围内？',
    choices: [
      { id: 'a', text: '本方禁区（罚球区）内' },
      { id: 'b', text: '整个球场任何地方' },
      { id: 'c', text: '只能在中圈' },
    ],
    answer: 'a',
    explanation: '守门员只能在自己的禁区内用手处理球，出了禁区用手就算手球犯规。',
  },
  {
    id: 'high-sports-021',
    subject: 'sports',
    prompt: '50米跑测试主要测的是什么能力？',
    choices: [
      { id: 'a', text: '短距离的速度' },
      { id: 'b', text: '长跑耐力' },
      { id: 'c', text: '柔韧性' },
    ],
    answer: 'a',
    explanation: '50米属于短跑，看的是谁起动快、跑得快，测的是速度。',
  },
  {
    id: 'high-sports-022',
    subject: 'sports',
    prompt: '羽毛球或乒乓球发球前，下面哪种习惯更有助于打得稳？',
    choices: [
      { id: 'a', text: '站好位置、放松握拍、看准球' },
      { id: 'b', text: '闭着眼睛随便挥' },
      { id: 'c', text: '用最大力气乱抡' },
    ],
    answer: 'a',
    explanation: '先站稳、放松、看准来球再出手，比一味用蛮力更容易打中、打稳。',
  },
]
