import type { BattleQuestion } from '../core'

export const items: BattleQuestion[] = [
  {
    id: 'low-sports-001',
    subject: 'sports',
    prompt: '踢足球的时候，我们主要用身体的哪个部位去踢球呀？',
    choices: [
      { id: 'a', text: '用手' },
      { id: 'b', text: '用脚' },
      { id: 'c', text: '用头顶' },
    ],
    answer: 'b',
    explanation: '足球主要用脚踢，守门员才可以用手哦。',
  },
  {
    id: 'low-sports-002',
    subject: 'sports',
    prompt: '打篮球的时候，我们要把球投进哪里才算得分？',
    choices: [
      { id: 'a', text: '投进篮筐' },
      { id: 'b', text: '踢进球门' },
      { id: 'c', text: '扔进水桶' },
    ],
    answer: 'a',
    explanation: '篮球要投进高高的篮筐里，进了就得分啦。',
  },
  {
    id: 'low-sports-003',
    subject: 'sports',
    prompt: '上体育课跑步之前，老师为什么先带大家做热身运动？',
    choices: [
      { id: 'a', text: '为了让身体活动开，不容易受伤' },
      { id: 'b', text: '为了浪费时间' },
      { id: 'c', text: '为了让大家睡觉' },
    ],
    answer: 'a',
    explanation: '先热身把身体活动开，跑起来才不容易拉伤、扭伤。',
  },
  {
    id: 'low-sports-004',
    subject: 'sports',
    prompt: '游泳的时候我们是在哪里活动呀？',
    choices: [
      { id: 'a', text: '在水里' },
      { id: 'b', text: '在树上' },
      { id: 'c', text: '在沙坑里' },
    ],
    answer: 'a',
    explanation: '游泳是在水里进行的运动，下水前要先做热身哦。',
  },
  {
    id: 'low-sports-005',
    subject: 'sports',
    prompt: '骑自行车的时候，为了保护头，我们最好戴上什么？',
    choices: [
      { id: 'a', text: '帽子手套' },
      { id: 'b', text: '头盔' },
      { id: 'c', text: '围巾' },
    ],
    answer: 'b',
    explanation: '骑车戴头盔，万一摔倒了也能保护我们的小脑袋。',
  },
  {
    id: 'low-sports-006',
    subject: 'sports',
    prompt: '小朋友跳绳的时候，绳子是用什么甩起来的？',
    choices: [
      { id: 'a', text: '用两只手甩' },
      { id: 'b', text: '用嘴巴咬' },
      { id: 'c', text: '用脚踢' },
    ],
    answer: 'a',
    explanation: '跳绳是两只手一起甩绳子，脚再一下一下跳过去。',
  },
  {
    id: 'low-sports-007',
    subject: 'sports',
    prompt: '运动出了很多汗，觉得口渴了，应该怎么办？',
    choices: [
      { id: 'a', text: '一口气喝很多冰水' },
      { id: 'b', text: '慢慢喝一点温水' },
      { id: 'c', text: '忍着不喝' },
    ],
    answer: 'b',
    explanation: '运动后慢慢喝点温水最舒服，喝太急或太冰肚子会不舒服。',
  },
  {
    id: 'low-sports-008',
    subject: 'sports',
    prompt: '乒乓球比赛里，我们用什么来打球？',
    choices: [
      { id: 'a', text: '球拍' },
      { id: 'b', text: '扫把' },
      { id: 'c', text: '勺子' },
    ],
    answer: 'a',
    explanation: '乒乓球要用小小的球拍来打，乒乒乓乓真好玩。',
  },
  {
    id: 'low-sports-009',
    subject: 'sports',
    prompt: '赛跑的时候，谁会先到达终点？',
    choices: [
      { id: 'a', text: '跑得最快的人' },
      { id: 'b', text: '跑得最慢的人' },
      { id: 'c', text: '站着不动的人' },
    ],
    answer: 'a',
    explanation: '赛跑就是比谁快，跑得最快的人最先冲过终点线。',
  },
  {
    id: 'low-sports-010',
    subject: 'sports',
    prompt: '羽毛球飞起来的时候，毛茸茸的那一头叫什么？',
    choices: [
      { id: 'a', text: '皮球' },
      { id: 'b', text: '毽子' },
      { id: 'c', text: '羽毛球' },
    ],
    answer: 'c',
    explanation: '羽毛球的一头白白软软像羽毛，用球拍打来打去。',
  },
  {
    id: 'low-sports-011',
    subject: 'sports',
    prompt: '上体育课，穿哪一种鞋子跑跳最合适？',
    choices: [
      { id: 'a', text: '运动鞋' },
      { id: 'b', text: '小皮鞋' },
      { id: 'c', text: '拖鞋' },
    ],
    answer: 'a',
    explanation: '运动鞋软软的、不打滑，跑跳起来又稳又舒服。',
  },
  {
    id: 'low-sports-012',
    subject: 'sports',
    prompt: '老鹰捉小鸡这个游戏里，小朋友们要做什么？',
    choices: [
      { id: 'a', text: '一直坐着' },
      { id: 'b', text: '排成一队躲老鹰' },
      { id: 'c', text: '闭着眼睛走路' },
    ],
    answer: 'b',
    explanation: '小鸡们排成一队跟着鸡妈妈，躲开来捉它们的老鹰。',
  },
  {
    id: 'low-sports-013',
    subject: 'sports',
    prompt: '小朋友踢毽子，毽子主要是用哪里踢的？',
    choices: [
      { id: 'a', text: '用脚的内侧踢' },
      { id: 'b', text: '用鼻子顶' },
      { id: 'c', text: '用耳朵接' },
    ],
    answer: 'a',
    explanation: '踢毽子常用脚的内侧轻轻踢，毽子就一上一下啦。',
  },
  {
    id: 'low-sports-014',
    subject: 'sports',
    prompt: '运动完了身体很累，回家应该怎么做才对身体好？',
    choices: [
      { id: 'a', text: '好好休息、早点睡觉' },
      { id: 'b', text: '通宵不睡接着玩' },
      { id: 'c', text: '一动也不动一整天' },
    ],
    answer: 'a',
    explanation: '运动后好好休息、睡个好觉，身体才长得壮壮的。',
  },
  {
    id: 'low-sports-015',
    subject: 'sports',
    prompt: '玩滑梯、爬攀爬架的时候，下面有什么会比较安全？',
    choices: [
      { id: 'a', text: '软软的垫子或沙子' },
      { id: 'b', text: '硬硬的石头' },
      { id: 'c', text: '尖尖的钉子' },
    ],
    answer: 'a',
    explanation: '下面铺软软的垫子或沙子，万一摔下来也没那么疼。',
  },
  {
    id: 'low-sports-016',
    subject: 'sports',
    prompt: '看图猜一猜：一个圆圆的球被踢进了有网的球门里，这是什么运动？',
    choices: [
      { id: 'a', text: '足球' },
      { id: 'b', text: '下棋' },
      { id: 'c', text: '画画' },
    ],
    answer: 'a',
    explanation: '把球踢进球门，这就是大家都爱玩的足球啦。',
  },
  {
    id: 'low-sports-017',
    subject: 'sports',
    prompt: '玩游戏时不小心摔倒了，膝盖有点疼，最先应该怎么办？',
    choices: [
      { id: 'a', text: '告诉老师或大人' },
      { id: 'b', text: '偷偷藏起来不说' },
      { id: 'c', text: '继续使劲跑' },
    ],
    answer: 'a',
    explanation: '受伤了要赶紧告诉老师或大人，让他们帮忙看一看。',
  },
  {
    id: 'low-sports-018',
    subject: 'sports',
    prompt: '小朋友拍皮球的时候，皮球碰到地面会怎么样？',
    choices: [
      { id: 'a', text: '弹起来' },
      { id: 'b', text: '飞到天上不下来' },
      { id: 'c', text: '变成方块' },
    ],
    answer: 'a',
    explanation: '皮球软软圆圆的，拍一下碰到地就一蹦一蹦弹起来。',
  },
  {
    id: 'low-sports-019',
    subject: 'sports',
    prompt: '冬天小朋友堆雪人、打雪仗，是在什么季节玩的运动？',
    choices: [
      { id: 'a', text: '夏天' },
      { id: 'b', text: '冬天' },
      { id: 'c', text: '什么时候都行' },
    ],
    answer: 'b',
    explanation: '只有冬天下雪了，才能堆雪人、打雪仗，玩得手都凉啦。',
  },
  {
    id: 'low-sports-020',
    subject: 'sports',
    prompt: '运动场上想要做得好，平时最应该怎么样？',
    choices: [
      { id: 'a', text: '多多练习' },
      { id: 'b', text: '从来不练' },
      { id: 'c', text: '只看别人玩' },
    ],
    answer: 'a',
    explanation: '只要多多练习，跑得就更快、跳得就更高啦。',
  },
  {
    id: 'low-sports-021',
    subject: 'sports',
    prompt: '做广播体操的时候，小朋友们应该怎么做？',
    choices: [
      { id: 'a', text: '跟着音乐认真做动作' },
      { id: 'b', text: '坐在地上不动' },
      { id: 'c', text: '互相推来推去' },
    ],
    answer: 'a',
    explanation: '广播体操要跟着音乐认真做，伸伸胳膊踢踢腿才有用。',
  },
  {
    id: 'low-sports-022',
    subject: 'sports',
    prompt: '比赛输了的时候，一个好朋友应该怎么做呀？',
    choices: [
      { id: 'a', text: '大哭大闹生气' },
      { id: 'b', text: '笑一笑，下次再加油' },
      { id: 'c', text: '怪别人不帮忙' },
    ],
    answer: 'b',
    explanation: '输了也没关系，笑一笑，下次再努力就好啦。',
  },
]
